cultuurnet/udb3-frontend

components/sidebar.vue
i18n/fr.json
i18n/nl.json
pages/manage/productions/index.vue

- Added sidebar link to productions overview page
- Removed unused `isJobLoggerStateIdle` computed property
---
Ticket: https://jira.uitdatabank.be/browse/III-3298

III-3298 Add sidebar link to productions overview page

---

api/api.js
api/events.js
components/sidebar.vue

- Added api method to get events to moderate
- Added amount of events to moderate to moderation link
- Fixed moderation link href
---
Ticket: https://jira.uitdatabank.be/browse/III-3398

III-3398 Moderation link

---

components/job/job-indicator.vue

- added bounceIn animation
---
Ticket: https://jira.uitdatabank.be/browse/III-3368

added bounceIn animation

---

assets/styles/_custom-bootstrap.scss
assets/styles/_global.scss
components/giftbox.vue
components/pagination.vue
components/sidebar.vue
i18n/fr.json
i18n/nl.json
layouts/default.vue
pages/*.vue
pages/manage/productions/create.vue
pages/manage/productions/index.vue

-  pagination component
-  button to create productions
-  stylings to match old angular app for productions
After changes:
---
Ticket: https://jira.uitdatabank.be/browse/III-3300

Feature/iii 3300 - productions overview

---

components/giftbox.vue
middleware/auth.js

- path to cookieOptions
- duplicate cookies of seenFeature, user and token
---
Ticket: https://jira.uitdatabank.be/browse/III-3404

feature/III-3404 - added path to cookieOptions to fix duplicate cookies of seenFeature, user and token

---

components/button-logout.vue
pages/login.vue

- change arrow-functions to normal functions to be able to use the context of this
-  login and logout creating an error

change arrow-functions to normal functions to be able to use the context of this

---

api/api.js
api/productions.js
components/productions/event.vue
components/productions/events.vue
i18n/fr.json
i18n/nl.json
pages/manage/productions/index.vue

- functionality to add individual events to a production
---
Ticket: https://jira.uitdatabank.be/browse/III-3302

add functionality to add individual events to a production

---

api/api.js
api/events.js
api/productions.js
components/productions/delete-modal.vue
components/productions/event.vue
components/productions/events.vue
i18n/fr.json
i18n/nl.json
pages/manage/productions/index.vue

- functionality to delete event from production
screenshot:
---
Ticket: https://jira.uitdatabank.be/browse/III-3304

add functionality to delete event from production

---

layouts/default.vue
pages/manage/productions/index.vue

- fix cursor pointer for a tags in productions

fix cursor pointer for a tags in productions

---

api/productions.js
assets/styles/_custom-bootstrap.scss
components/productions/productions.vue
components/productions/search.vue
i18n/fr.json
i18n/nl.json
package.json
pages/manage/productions/index.vue
yarn.lock

- search for productions
---
Ticket: https://jira.uitdatabank.be/browse/III-3301

add search for productions

---

api/api.js
api/events.js
api/productions.js
assets/suggested-events.js
components/productions/create/event.vue
components/productions/index/event.vue
pages/manage/productions/create.vue

- logic for button skip
---
Ticket: https://jira.uitdatabank.be/browse/III-3311

Feature/iii 3311 - Add logic for button skip

---

pages/login.vue
services/auth.js

- Fixed the login link for `fr` users
---
Ticket: https://jira.uitdatabank.be/browse/III-3419

III-3419 Make lang parameter of login link customizable

---

.github/pull_request_template.md
.github/workflows/ci.yml
README.md
api/api.js
api/productions.js
layouts/default.vue
package.json
pages/manage/productions/create.vue

- Added functionality to link two events that do not belong to a production, in either a new production or an existing one
---
Ticket: https://jira.uitdatabank.be/browse/III-3315

feature/III-3315 - add functionality to link events to existing production

---

components/productions/create/event.vue
i18n/fr.json
i18n/nl.json
pages/manage/productions/create.vue

- When an event is already linked to a production, we must link the other event to that production
---
Ticket: https://jira.uitdatabank.be/browse/III-3313

Linking when 1 event is already linked to a production

---

components/giftbox.vue

- change text-transform on action button in giftbox
---
Ticket: https://jira.uitdatabank.be/browse/III-3437

Fix text-transform in giftbox

---

components/productions/index/event.vue
components/productions/index/events.vue
i18n/fr.json
i18n/nl.json

- type in event detail
- data format to small
- title from event detail
---
Ticket: https://jira.uitdatabank.be/browse/III-3447

Several tweaks to event detail

---

components/productions/index/events.vue
components/productions/index/productions.vue
layouts/default.vue
pages/manage/productions/index.vue

- limit number of productions on a page to 15
---
Ticket: https://jira.uitdatabank.be/browse/III-3449

Limit to 15 productions on a page

---

i18n/fr.json
i18n/nl.json

- productions info copy changes
---
Ticket: https://jira.uitdatabank.be/browse/III-3301

changed productions info copy

---

package.json
pages/manage/productions/create.vue
yarn.lock

- use vue-typeahead-bootstrap for autocomplete
---
Ticket: https://jira.uitdatabank.be/browse/III-3450

Use third party solution for autocomplete

---

pages/manage/productions/index.vue

- fix if statement
---
Ticket: https://jira.uitdatabank.be/browse/III-3454

Make sure pagination is shown when there is one production

---

api/productions.js

- Retrieve data from events key in returned data
---
Ticket: https://jira.uitdatabank.be/browse/III-3464

Retrieve events from events key in data

---

assets/styles/global.scss

- Removed wrapper class in global
---
Ticket: https://jira.uitdatabank.be/browse/III-3457

III-3457 - Removed wrapper class in global

---

components/productions/index/productions.vue
publiq-ui/pub-pagination.stories.mdx
publiq-ui/pub-pagination.vue

- added pub-pagination component
- added story for pub-pagination
---
Ticket: https://jira.uitdatabank.be/browse/III-3457

Feature/iii 3457 add pub-pagination

---

.github/pull_request_template.md
api/productions.js
functions/getMockedEventsSet.js
pages/manage/productions/create.vue

- Add similarity score on events create page
Ticket: https://jira.uitdatabank.be/browse/III-3465

Feature/iii 3465 Add similarityScore on events

---

components/productions/create/event.vue
i18n/nl.json
pages/manage/productions/create.vue

- truncate the description on 750 chars
- align title styling
- use sm data format for event
- remove max-width on the container
- fixed missing translation
---
Ticket: https://jira.uitdatabank.be/browse/III-3468

Feature/iii 3468 Visual fixes on productions create page

---

components/productions/create/event.vue
package.json
yarn.lock

- use textarea trick for HTML entities
---
Ticket: https://jira.uitdatabank.be/browse/III-3472

Use textarea trick for html entities

---

nuxt.config.js
publiq-ui/docs/design-principles.stories.mdx
publiq-ui/pub-button.stories.mdx
publiq-ui/pub-h1.stories.mdx
publiq-ui/pub-list.stories.mdx
publiq-ui/pub-loading-spinner.stories.mdx
publiq-ui/pub-pagination.stories.mdx
publiq-ui/pub-panel.stories.mdx
publiq-ui/pub-wrapper.stories.mdx

- Documented the design principles
- Grouped the components under the `Components` header to fix the sorting in the sidebar

Document design principles

---

components/productions/index/events.vue
i18n/fr.json
i18n/nl.json
pages/manage/productions/create.vue
pages/manage/productions/index.vue
publiq-ui/pub-alert.stories.mdx
publiq-ui/pub-alert.vue

- add error message when a event is being added that already exists
---
Ticket: https://jira.uitdatabank.be/browse/III-3459

Feature/iii 3459 - show error message when a event is being added that already exists

---

pages/manage/productions/create.vue

- position relative to input container 
Should fix the 2 tickets below
---
Ticket: 
https://jira.uitdatabank.be/browse/III-3477
https://jira.uitdatabank.be/browse/III-3467

Add position relative to input container

---

components/productions/index/event.vue

- provide width for the table headers
---
Ticket: https://jira.uitdatabank.be/browse/III-3483

Set a width for the table headers

---

components/productions/index/search.vue

fix width label

---

.github/workflows/chromatic.yml
.gitignore
package.json
yarn.lock

- Chromatic integration to deploy Storybook
---
Ticket: https://jira.uitdatabank.be/browse/III-3504

III-3504 Storybook deployment

---

publiq-ui/pub-input.vue

- fix error "Property or method "value" is not defined"

fix error "Property or method "value" is not defined"

---

i18n/fr.json
i18n/nl.json

- translations 
---
Ticket: https://jira.uitdatabank.be/browse/III-3563
After changes:

III-3563 - change translations

---

.storybook/preview.js

- alphabetic sorting of components
---

Sort components alphabetically

---

src/components/publiq-ui/Badge.js
src/components/publiq-ui/Container.js
src/components/publiq-ui/Input.js
src/components/publiq-ui/ListItem.js
src/components/publiq-ui/Pagination.js

- required props 
- defaultProps
---

Feature/iii 3588 required props and defaultProps

---

src/components/publiq-ui/Checkbox.stories.mdx
src/components/publiq-ui/ModalContent.stories.mdx
src/components/publiq-ui/ModalQuestion.stories.mdx
src/components/publiq-ui/Pagination.stories.mdx

- Rename actions for consistency
---

III-3588 - Rename actions for consistency

---

.storybook/CustomCanvas.js
.storybook/preview.js

- CustomCanvas component
- Layout of codeblock in storybook
- Unreadable text in codeblock
---

III-3588 - Create customCanvas to improve readability codeblock

---

src/components/publiq-ui/Link.js
src/components/publiq-ui/Link.stories.mdx
src/components/publiq-ui/theme.js

- Link component with different storybook scenarios
---

III-3588 / Add link component

---

src/pages/[...params].js
src/pages/_app.js
src/pages/manage/productions/index.js

- Fixed redirect issue after login

Fix redirect issue

---

package.json
src/components/LoginButton.js
src/components/SideBar.js
src/hooks/api/events.js
src/hooks/api/useAuthenticatedQuery.js
src/hooks/api/user.js
src/pages/_app.js
src/pages/login/index.js
yarn.lock

Fix redirect to login

---

src/hooks/api/events.js
src/hooks/api/useAuthenticatedQuery.js
src/hooks/api/user.js

- Fixed wrong way of passing down configuration in react-query

Fix faulty configuration

---

src/components/joblogger/JobLogger.js

- overlay opacity
---
Ticket: https://jira.uitdatabank.be/browse/III-3599
After change:

Fix overlay opacity

---

src/pages/_app.js

- home Icon appearing on initial render
---
Ticket: https://jira.uitdatabank.be/browse/III-3592

Fix home Icon appearing

---

src/components/joblogger/JobLogger.js

- z index issue
---
Ticket: https://jira.uitdatabank.be/browse/III-3590
Screenshot before:
Screenshot after:

fix z-index issue

---

src/hooks/useHandleWindowMessage.js
src/pages/_app.js

- listening for messages from old angular app for potential redirect
---
Ticket: https://jira.uitdatabank.be/browse/III-3589
Related PR: https://github.com/cultuurnet/udb3-angular/pull/626

Listen for WindowMessageTypes.HTTP_STATUS_CODE

---

src/pages/[...params].js
src/pages/manage/productions/index.js
src/utils/getApplicationServerSideProps.js

Create getApplicationServerSideProps function

---

src/components/manage/productions/create/Event.js
src/components/publiq-ui/Typeahead.js
src/components/publiq-ui/Typeahead.stories.mdx
src/components/publiq-ui/TypeaheadWithLabel.js
src/components/publiq-ui/TypeaheadWithLabel.stories.mdx
src/hooks/api/productions.js
src/pages/manage/productions/create.js
src/pages/manage/productions/index.js
src/utils/getApplicationServerSideProps.js

- fixed some productions issues
- prefetch user, permissions and roles
-

Several smaller fixes for productions

---

src/pages/manage/productions/create.js
src/pages/manage/productions/index.js

- add dependencies for productions on productions index page
- fix issue with manipulating input on create page
- fix debounces

Recalculate productions on new results

---

src/pages/manage/productions/create.js
src/pages/manage/productions/index.js

- use throttle instead of debounce
- reset page when searching

Throttle / pagination issue

---

src/pages/login/[language].js

- fix broken getServerSideProps

Fix broken getServerSideProps

---

src/components/SideBar.js
src/pages/_app.js

- Scrolling issue sidebar
---
Ticket: https://jira.uitdatabank.be/browse/III-3684

III-3684 - Fix scrolling issue SideBar

---

src/i18n/fr.json

- fr translation
---
Ticket: https://jira.uitdatabank.be/browse/III-3626

Update fr translations to match angular changes

---

src/components/SideBar.js

- width that was changing of sidebar when scaling webbrowser
---
Ticket: https://jira.uitdatabank.be/browse/III-3684

Fix sidebar width issue

---

package.json
src/utils/getApplicationServerSideProps.js
yarn.lock

- Redirect to auth page when token is expired
---
Ticket: https://jira.uitdatabank.be/browse/III-3683

Redirect when token is expired

---

src/components/manage/productions/index/Events.js
src/i18n/nl.json
src/pages/_app.js
src/pages/manage/productions/index.js

- empty state for events
- moved spinner
- correct translation

Move spinner and add empty data state on productions page

---

src/components/SideBar.js

- Added check on sidebar menu items to hide giftbox menu item if not using Dutch
***
Ticket: https://jira.uitdatabank.be/browse/III-3695

Don't show giftbox menu in sidebar when not using Dutch

---

src/components/manage/productions/create/Event.js
src/components/manage/productions/index/Events.js
src/components/offerStatus/StatusFormOnPage.js
src/components/offerStatus/StatusModal.js
src/components/offerStatus/constants.js
src/constants/CalendarType.js
src/constants/OfferType.js
src/pages/event/[eventId]/status.js

- `src/pages/event/[eventId]/status.js` to show StatusFormOnPage
- Use constants CalendarType and OfferType
---
Ticket: https://jira.uitdatabank.be/browse/III-3576
Screenshot:

III-3576 - Status UI for single, permanent and periodic

---

src/components/publiq-ui/Card.stories.mdx
src/components/publiq-ui/Link.js

Storybook: Fix card story and Link story

---

.github/workflows/chromatic.yml

- Disabled chromatic job for dependabot PRs

Disable chromatic job for dependabot PRs

---

src/components/pages/manage/productions/create/index.js

- loading state for link button
- disabled state for skip button
- disabled state for skip button
---
Ticket: https://jira.uitdatabank.be/browse/III-3793
Screenshot:

Add loading state and disabled state when linking or when skipping

---

src/components/StatusPageMultiple.js
src/components/pages/manage/productions/create/Event.js
src/components/pages/manage/productions/create/index.js
src/components/pages/manage/productions/index/index.js
src/ui/Box.js
src/ui/Inline.js
src/ui/SelectionTable.js
src/ui/Stack.js
src/utils/formatPeriod.js

- Lodash imports
Reference: [lodash-import-done-right](https://dev.to/icokie/lodash-import-done-right-290n)

Improvement - Make all Lodash imports the same

---

src/ui/TextArea.js
src/ui/TextArea.stories.mdx
src/ui/theme.js

- Added padding to TextArea
---
Ticket: https://jira.uitdatabank.be/browse/III-3847
---
Padding example:

III-3847 Add padding to TextArea

---

src/components/pages/manage/productions/create/index.js

- Trigger production search after entering at least 3 characters
---
Ticket: https://jira.uitdatabank.be/browse/III-3893

III-3893 Trigger production search after entering 3 characters

---

next.config.js
package.json
src/components/layouts/ErrorFallback.js
src/components/layouts/index.js
src/components/pages/_app.js
src/constants/FeatureFlags.js
src/hooks/useCookiesWithOptions.js
src/hooks/useFeatureFlag.js
src/pages/500.js
yarn.lock

- Simple hook to check if a feature flag is enabled and set it
- constants to use in code
- helper for the browser console
- custom 500 page
```js
setFeatureFlag(FeatureFlags.REACT_DASHBOARD, false)
```
- Next to 10.1 and using Webpack 5 now

Feature flags setup

---

src/components/layouts/Sidebar.js
src/components/pages/create.js
src/hooks/useFeatureFlag.js
src/pages/create.js

- `/create` page
- use feature flag to switch path in navigation
- [Removed ...]
- convert string to boolean in useFeatureFlag
---
Ticket: https://jira.uitdatabank.be/browse/III-3949

[III-3949] Port create/edit form to React

---

src/components/pages/_app.js

Fix typo in title

---

src/ui/Badge.js
src/ui/Badge.stories.mdx

- Added secondary badge flavour
---
Ticket: https://jira.uitdatabank.be/browse/III-3943

III-3943 Add secondary badge flavour

---

src/components/StatusPageMultiple.js
src/components/layouts/Announcements.js
src/components/layouts/joblogger/Job.js
src/ui/Button.js
src/ui/Link.js
src/ui/Link.stories.mdx

- Added `Button` variants for `Link` component
- Changed existing usages of `<Link><Button>` to use Button Link-Variants

Add Button variants for Link component

---

src/ui/docs/DesignPrinciples.stories.mdx

- Fixed typo in Storybook documentation

Fix typo in Storybook documentation

---

src/utils/getApplicationServerSideProps.js

- Fixed TLS errors in SSR when running a local production build

Fix TLS errors in local production builds

---

src/hooks/useMatchBreakpoint.js

- safari bug
---
Ticket: https://jira.uitdatabank.be/browse/III-3981

III-3981 - Add extra check

---

src/hooks/useEventListenerOnMediaQuery.js
src/hooks/useMatchBreakpoint.js

- hook
- Safari bug
---
Ticket: https://jira.uitdatabank.be/browse/III-3981

III-3981 - Fix safari bug

---

src/components/pages/login/[language].js
src/i18n/fr.json
src/i18n/nl.json

- Changed agenda count from 500 to 1000
---
Ticket: https://jira.uitdatabank.be/browse/III-3957

III-3957 Change agenda count from 500 to 1000

---

src/components/layouts/Sidebar.js
src/components/layouts/joblogger/JobLogger.js
src/components/pages/_app.js
src/styles/GlobalStyle.js
src/ui/Modal/ContentModal.js
src/ui/Modal/QuestionModal.js
src/ui/theme.ts

- z-index management
---
Approach based on this article: https://www.smashingmagazine.com/2021/02/css-z-index-large-projects/

Improve z index management

---

src/components/pages/login/[language].js
src/components/pages/login/index.js
src/utils/getApplicationServerSideProps.js

- Use referer to know what url to return to after login
---
Ticket: https://jira.uitdatabank.be/browse/III-3944

III-3944 - Use referer to know what url to return to after login

---

package.json
src/components/pages/login/index.js
src/utils/getApplicationServerSideProps.js
yarn.lock

- Host url not being correct
---
Ticket: https://jira.uitdatabank.be/browse/III-3944

III-3944 redirect to original url (follow up)

---

src/utils/getApplicationServerSideProps.js

- User cannot log on in UiTdatabank because of referer points to different webstie
---
Ticket: https://jira.uitdatabank.be/browse/III-4016

III-4016 - Referer bug (from google)

---

src/components/pages/login/index.js
src/utils/getApplicationServerSideProps.js

- Double encode the plus sign to avoid conversion to space
---
Ticket: https://jira.uitdatabank.be/browse/III-4041

III-4041 Fix plus sign encoding issue

---

src/hooks/api/user.js
src/utils/getApplicationServerSideProps.js

- api call server side for user
- toString function for Cookies
---
Ticket: https://jira.uitdatabank.be/browse/III-3943

III-3943 - Fix user in serverside

---

src/utils/getApplicationServerSideProps.js

- token being unknown in the request

Fix prefetching on serverside (followup)

---

src/components/pages/dashboard.tsx
src/hooks/api/user.js
src/i18n/fr.json
src/i18n/nl.json
src/redirects.js
src/ui/Dropdown.tsx
src/utils/getApplicationServerSideProps.js

- delete action for organizer
- no_items translations
- dropdown items to use Button and Link behind the scenes
- unused file createDashboard
---
Ticket: https://jira.uitdatabank.be/browse/III-3961

III-3961 - organizer tab last improvements

---

src/utils/getApplicationServerSideProps.js

Fix for redirect issue

---

src/components/pages/dashboard/index.tsx

- Delete button for organizer
---
Ticket: https://jira.uitdatabank.be/browse/III-3961
Screenshot:

Remove delete button for organizer

---

src/components/pages/dashboard/NewsletterSingupForm.tsx
src/components/pages/dashboard/index.tsx
src/i18n/fr.json
src/i18n/nl.json

- copy changes
- double contact us link
---
https://jira.uitdatabank.be/browse/III-4079
https://jira.uitdatabank.be/browse/III-4081

Several fixes for Dashboard

---

src/ui/Pagination.tsx
src/ui/theme.ts

- z index of pagination active page link
Problem screenshot:

Fix z index of pagination active page link

---

src/components/pages/dashboard/NewsletterSingupForm.tsx

- placeholder on the newsletter section
---
Ticket: https://jira.uitdatabank.be/browse/III-4089

Change placeholder copy on newsletter section on dashboard

---

src/components/pages/dashboard/index.tsx
src/hooks/api/events.ts
src/hooks/api/places.ts

- sm-text instead of md-text
---
Ticket: https://jira.uitdatabank.be/browse/III-4090

III-4090 - Use sm-text instead of md-text

---

src/components/StatusPageSingle.js

- Make it possible to save when only deleting the description
---
Ticket: https://jira.uitdatabank.be/browse/III-4038

III-4038 - Make it possible to save when only deleting the description of status

---

src/components/pages/manage/productions/create/index.js

- radiobutton not being selected
---
Ticket: https://jira.uitdatabank.be/browse/III-3909
Screenshot:

III-3909 - Fix radiobutton not being selected

---

.storybook/preview-head.html
src/components/pages/_document.js

- font optimization
---
Ticket: https://jira.uitdatabank.be/browse/III-3789

III-3789 - Fix font optimization

---

src/components/pages/dashboard/index.tsx
src/i18n/fr.json
src/i18n/nl.json

- Copy for empty states on dashboard
---
Ticket: https://jira.uitdatabank.be/browse/III-4100

Copy changes for empty states dashboard

---

src/components/layouts/Sidebar.js
src/components/pages/dashboard/index.tsx
src/hooks/useFeatureFlag.ts
src/pages/dashboard.tsx
src/redirects.js

- feature flag REACT_DASHBOARD
---
Ticket: https://jira.uitdatabank.be/browse/III-4102

III-4102 - Remove feature flag REACT_DASHBOARD

---

src/components/pages/dashboard/index.tsx

- preview url organizer
---
Ticket: https://jira.uitdatabank.be/browse/III-4107
Screenshot:

III-4107 - Fix wrong link organizers

---

.github/workflows/ci.yml

Add extra types check CI

---

src/machines/movie.ts

- state diagdram for Step 1 entry form movies
---
[Link to state diagram](https://xstate.js.org/viz/?gist=803694e3343002a2109b90ba4bd10c71)
[StateX docs](https://xstate.js.org/docs/guides/typescript.html#using-typescript)
Ticket: https://jira.uitdatabank.be/browse/III-3544

III-3544 - Add state diagram filminvoer step 1

---

src/components/pages/dashboard/NewsletterSingupForm.tsx
src/hooks/api/newsletter.ts
src/ui/Panel.tsx

- mailing list id on test
- validation of email field
- duplicate put request
- success message
---
Ticket: https://jira.uitdatabank.be/browse/III-4091

III-4091 - Fix cors issue

---

src/components/pages/dashboard/NewsletterSingupForm.tsx

- newsletter form
---
Ticket: https://jira.uitdatabank.be/browse/III-4091

III-4091 - Fix CORS issue newsletter form

---

.eslintrc
package.json
yarn.lock

- new plugin and rule to auto fix unused imports

Add new plugin and rule to auto fix unused imports

---

src/components/pages/manage/movies/Step4Content.tsx
src/components/pages/manage/movies/create.tsx
src/hooks/api/authenticated-query.ts
src/hooks/api/productions.ts
src/i18n/nl.json
src/machines/movie.ts
src/types/Event.ts
src/types/Production.ts
src/ui/Typeahead.tsx

- [Added ...]
- [Changed ...]
- [Removed ...]
- [Fixed ...]
---

Iii 3535 step 4

---

src/ui/Link.tsx

Fix Link story

---

src/components/AvailabilityPageMultiple.js
src/components/AvailabilityPageSingle.js
src/components/BookingAvailabilityForm.js
src/components/BookingAvailabilityModal.js
src/components/StatusForm.js
src/components/StatusModal.js
src/components/pages/events/[eventId]/availability.multiple.test.js
src/constants/BookingAvailabilityType.ts
src/hooks/api/events.ts
src/i18n/fr.json
src/i18n/nl.json
src/test/data/event.js
src/test/data/place.js
src/types/Offer.ts
src/ui/SelectionTable.js

- Patch the booking availability of an event with multiple calendar type
---
Ticket: https://jira.uitdatabank.be/browse/III-4046

III-4046 Patch the booking availability of an event with multiple calendar type

---

src/components/pages/events/[eventId]/availability.multiple.test.js
src/components/pages/events/[eventId]/availability.single.test.js
src/components/pages/places/[placeId]/availability.test.js
src/i18n/fr.json
src/i18n/nl.json

- Tweak copy for status and booking
Note: See ticket [comment](https://jira.uitdatabank.be/browse/III-4046?focusedCommentId=113181&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-113181) for details
---
Ticket: https://jira.uitdatabank.be/browse/III-4046

III-4046 Tweak copy for status and booking

---

src/components/layouts/Announcements.js

- Announcements
---
Ticket: https://jira.uitdatabank.be/browse/III-4219

III-4219 - Fix announcements crashing

---

src/components/AvailabilityPageSingle.js
src/components/BookingAvailabilityForm.js
src/components/StatusForm.js
src/ui/RadioButtonGroup.js
src/ui/RadioButtonGroup.stories.mdx
src/ui/Title.stories.mdx
src/ui/Title.tsx
src/ui/theme.ts

- Make radio button group label optional
- Add title component for status and booking on the single calendar page
---
Ticket: https://jira.uitdatabank.be/browse/III-4045

III-4045 UI improvements to match mockups for availability of single calendar type

---

src/i18n/de.json

- german translations
---
Ticket: https://jira.uitdatabank.be/browse/III-4253

III-4253 - Add german translations

---

src/components/layouts/Sidebar.tsx

- manageMenu not updating language when different language is chosen
Ticket: https://jira.uitdatabank.be/browse/III-4253

III-4253 - Fix manageMenu not updating language when different language is chosen

---

src/ui/Page.tsx

- footer not staying at bottom
---
before:
after:

Fix footer not staying at bottom

---

src/components/Footer.tsx
src/hooks/useFeatureFlag.ts

- feature flag german translations
---
Ticket: https://jira.uitdatabank.be/browse/III-4332
Screenshots:

III-4332 - Enable languager picker German for everyone

---

src/i18n/fr.json
src/i18n/nl.json

'Deutch' into 'Deutsch'
---
Ticket: https://jira.uitdatabank.be/browse/III-4418

Fix 'Deutch' typo

---

src/i18n/nl.json

- title of step4 of filminvoer
---

III-4340 - Update copy

---

src/components/pages/manage/productions/index/index.js

- broken search on productions page
---
It had to do with this change:
https://github.com/cultuurnet/udb3-frontend/commit/2bbb0fa7cacf89e7c41450d860c78d1dd073922a#diff-fab2006aa4aa6ff773eac3db6a89bf2d03f488a103b43d0f2b9e7a8d7f027904
Ticket: https://jira.uitdatabank.be/browse/III-4452

III-4452 - Fix crashing search productions

---

src/ui/TimeTable.tsx

-  Startdate of calendar in filminvoer ui starts on wednesdays
---
Ticket: https://jira.uitdatabank.be/browse/III-4451

III-4451 - Startdate of calendar in filminvoer ui starts on wednesdays

---

src/components/layouts/Sidebar.tsx
src/components/pages/dashboard/index.tsx
src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json
src/redirects.tsx
src/ui/Select.stories.mdx
src/ui/Select.tsx

- custom `Select` component
- sorting option on dashboard
---
Ticket: https://jira.uitdatabank.be/browse/III-4490

III-4490 - Add sort functionality on dashboard

---

src/components/pages/dashboard/index.tsx

- Only show sorting select on event tab
---
Ticket: https://jira.uitdatabank.be/browse/III-4490

III-4490 - Only show sorting select on event tab

---

src/components/pages/manage/movies/Step2.tsx
src/components/pages/manage/movies/Step5.tsx
src/components/pages/manage/productions/index/Events.js
src/ui/Box.tsx
src/ui/FormElement.tsx
src/ui/Inline.tsx
src/ui/RadioButtonGroup.js
src/ui/Stack.tsx

- added typing to properties like justifyContent, display, flexWrap, ...
- made it possible to use `condition && <... />` again instead of having to do `condition ? <... /> : null`

Improvements design system

---

src/pages/dashboard/index.page.tsx

- prefetching of events on dashboard page with the correct sorting
- Missing Footer and Newsletter sign up box on /dashboard

Fix initial ssr dashboard

---

src/pages/manage/productions/index.page.js

- Broken pagination
- Broken selection of 1st production on new page

Broken pagination and 1st production select fix (productions)

---

src/pages/manage/productions/create/index.page.js
src/ui/Typeahead.tsx

- **Scenario**: One of the events belong to a production => admin user can link the events to the existing production, or skip the suggested pair
---
Ticket: https://jira.uitdatabank.be/browse/III-4604

III-4604 - Fix similairity ui

---

src/hooks/api/events.ts
src/pages/Steps.tsx
src/pages/create/CalendarStep.tsx
src/pages/create/EventForm.tsx
src/pages/create/ThemeStep.tsx
src/pages/create/TypeStep.tsx
src/pages/create/index.page.tsx
src/pages/manage/movies/AdditionalInformationStep.tsx
src/pages/manage/movies/CinemaStep.tsx
src/pages/manage/movies/MovieForm.tsx
src/pages/manage/movies/MoviePage.tsx
src/pages/manage/movies/NameStep.tsx
src/pages/manage/movies/ProductionStep.tsx
src/pages/manage/movies/ThemeStep.tsx
src/pages/manage/movies/TimeTableStep.tsx
src/pages/manage/movies/[eventId]/edit.page.tsx
src/pages/manage/movies/create.page.tsx

- create page with type / theme and calendar step placeholders

Setup Create page

---

src/pages/Steps.tsx
src/pages/create/CalendarStep.tsx
src/pages/create/ThemeStep.tsx
src/pages/create/TypeStep.tsx
src/pages/steps/EventTypeAndThemeStep.tsx
src/pages/steps/PlaceStep.tsx
src/pages/steps/ProductionStep.tsx
src/pages/steps/TimeTableStep.tsx

- better typing for FormData passed to Controller and useForm
---
Ticket: https://jira.uitdatabank.be/browse/III-3949

III-3949 - Better types FormData

---

src/i18n/nl.json
src/pages/Steps.tsx
src/pages/manage/movies/MovieForm.tsx
src/pages/steps/AdditionalInformationStep.tsx
src/pages/steps/EventTypeAndThemeStep.tsx
src/pages/steps/PlaceStep.tsx
src/pages/steps/ProductionStep.tsx
src/pages/steps/modals/PictureUploadModal.tsx
src/ui/Box.tsx
src/ui/FormElement.tsx
src/ui/ProgressBar.stories.mdx
src/ui/ProgressBar.tsx
src/ui/theme.ts

- New `ProgressBar` component
- Show ProgressBar below the description text area
- Show info alert below the description based on the eventType id
- Rename movie specific translation keys to create
- Move movie theme to more generic createPage theme
- Remove unused import
- Only add theme to payload when it is defined
- Description when clearing wasn't updating
---
Ticket: https://jira.uitdatabank.be/browse/III-4476

III-4475 - Additional information step - description

---

src/pages/create/TypeStep.tsx
src/ui/Box.tsx
src/ui/ToggleBox.tsx

- improvements togglebox
---
Ticket: https://jira.uitdatabank.be/browse/III-4488
Screenshots:

III-4488 - Improvements togglebox

---

src/pages/manage/movies/MovieForm.tsx
src/pages/steps/AdditionalInformationStep.tsx

- variant for AdditionalInformationStep
---
Ticket: https://jira.uitdatabank.be/browse/III-4475

III-4475 - Add variant to additional information step

---

src/pages/create/EventForm.tsx

- show AdditionalInformationStep on EventForm with dummy id
---
Ticket: https://jira.uitdatabank.be/browse/III-4478

III-4478 - Add AdditionalInformationStep to EventForm with dummy id

---

src/pages/manage/movies/MovieForm.tsx

- Issue with edit page. The save button reappeared when there was an error in the form

Switch to AUTO_SAVE mode when on edit page

---

src/hooks/api/announcements.js
src/hooks/api/events.ts
src/hooks/api/images.ts
src/hooks/api/newsletter.ts
src/hooks/api/organizers.ts
src/hooks/api/places.ts
src/hooks/api/productions.ts
src/hooks/api/themes.ts
src/hooks/api/user.js
src/layouts/Sidebar.tsx
src/layouts/index.js
src/pages/AvailabilityPageMultiple.js
src/pages/AvailabilityPageSingle.js
src/pages/dashboard/NewsletterSingupForm.tsx
src/pages/dashboard/index.page.tsx
src/pages/events/[eventId]/availability.page.js
src/pages/manage/movies/MovieForm.tsx
src/pages/manage/movies/[eventId]/edit.page.tsx
src/pages/manage/productions/Events.js
src/pages/manage/productions/create/Event.js
src/pages/manage/productions/create/index.page.js
src/pages/manage/productions/index.page.js
src/pages/places/[placeId]/availability.page.js
src/pages/steps/AdditionalInformationStep.tsx
src/pages/steps/EventTypeAndThemeStep.tsx
src/pages/steps/ProductionStep.tsx
src/utils/getApplicationServerSideProps.js

- Added Query and Mutation suffix on data fetching hooks

Rename mutation and query hooks

---

src/pages/steps/AdditionalInformationStep.tsx
src/ui/Button.tsx
src/ui/TimeTable.tsx

- Show video upload in movie form
- Import from lodash the best way
- Button align-items
Behaviour different between firefox and chrome.
**Before:**
**After:**
---
Ticket: https://jira.uitdatabank.be/browse/III-4478

III-4478 - Show video upload in movie form

---

src/pages/PictureUploadBox.tsx
src/pages/steps/AdditionalInformationStep.tsx
src/pages/steps/modals/PictureUploadModal.tsx
src/pages/steps/modals/PriceInfoModal.tsx
src/ui/Box.tsx

III-4632 - Drag and drop images

---

.eslintrc
next-env.d.ts
package.json
src/hooks/api/organizers.ts
src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json
src/pages/create/EventForm.tsx
src/pages/manage/movies/MovieForm.tsx
src/pages/manage/movies/useEditField.ts
src/pages/steps/AdditionalInformationStep.tsx
src/pages/steps/OrganizerPicker.tsx
src/pages/steps/PlaceStep.tsx
src/pages/steps/PriceInformation.tsx
src/pages/steps/ProductionStep.tsx
src/pages/steps/modals/PictureUploadModal.tsx
src/ui/Typeahead.tsx
yarn.lock

- organizer select
- get organizers api hook
- unused-imports eslint rule
- better typing Typeahead
---
Ticket: https://jira.uitdatabank.be/browse/III-4479

III-4479 - Add organizer select

---

src/constants/EventTypes.ts
src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json

- Add Speeltuin to react frontend
---
Ticket: https://jira.uitdatabank.be/browse/III-4588

III-4588 - Add Speeltuin to react frontend

---

src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json
src/pages/steps/AdditionalInformationStep.tsx
src/pages/steps/DescriptionStep.tsx
src/pages/steps/Steps.tsx
src/ui/Box.tsx
src/ui/FormElement.tsx
src/ui/ProgressBar.tsx
src/ui/Tabs.tsx
src/ui/TextArea.tsx

- Move steps of AdditionalInformation under tabs
- Move DescriptionStep into separate component/file
- Fix description input lagging by moving DescriptionStep into separate component/file
---
Ticket: https://jira.uitdatabank.be/browse/III-4475
⚠️ In the next PR I will separate all steps of AdditionalInformation, like I did here for Description. My goal will also be to clean up tabsConfigurations, since right now it has a large dependency array.

III-4475 - Add tabs additional information

---

src/types/Event.ts
src/types/Place.ts

-  less strict checks @context
---
Ticket: https://jira.uitdatabank.be/browse/DDT-39

DDT-39 - Add less strict checks @context

---

src/hooks/api/organizers.ts
src/pages/OrganizerAddModal.tsx
src/pages/steps/AdditionalInformationStep.tsx
src/pages/steps/ContactInfoEntry.tsx
src/pages/steps/OrganizerStep.tsx

- contact info to organizer modal
---
Ticket: https://jira.uitdatabank.be/browse/III-4846

III-4846 - Add contact info to organizer modal

---

src/pages/steps/AdditionalInformationStep.tsx
src/pages/steps/EventTypeAndThemeStep.tsx
src/pages/steps/PlaceStep.tsx
src/pages/steps/ProductionStep.tsx
src/pages/steps/ScopeStep.tsx
src/pages/steps/Steps.tsx
src/pages/steps/TimeTableStep.tsx

- [Refactor steps to use shouldShowStep](https://github.com/cultuurnet/udb3-frontend/commit/95da2d93ae58cb40c0c1bad0462da39b0bcb64fd)
- Hide ScopeStep if type has been chosen
---
Ticket: https://jira.uitdatabank.be/browse/III-4488

III-4488 - Hide ScopeStep if type has been chosen

---

src/hooks/api/terms.ts
src/layouts/index.js
src/pages/events/[eventId]/availability.multiple.test.js
src/pages/events/[eventId]/availability.single.test.js
src/pages/places/[placeId]/availability.test.js

- Only fetch terms once in the layout

Only fetch terms once in the layout

---

src/hooks/api/cities.ts
src/hooks/api/events.ts
src/hooks/api/places.ts
src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json
src/pages/create/EventForm.tsx
src/pages/manage/movies/MovieForm.tsx
src/pages/steps/AdditionalInformationStep.tsx
src/pages/steps/EventTypeAndThemeStep.tsx
src/pages/steps/MunicipalityAndPlaceStep.tsx
src/pages/steps/NameAndAgeRangeStep.tsx
src/pages/steps/PlaceStep.tsx
src/pages/steps/ProductionStep.tsx
src/pages/steps/ScopeStep.tsx
src/pages/steps/Steps.tsx
src/pages/steps/StepsForm.tsx
src/pages/steps/TimeTableStep.tsx
src/pages/steps/hooks/useEditField.ts
src/pages/steps/hooks/useParseStepConfiguration.ts
src/ui/Typeahead.tsx

- location step 
- Fix type and theme editing
---
Ticket: https://jira.uitdatabank.be/browse/III-4473

III-4473 - step3: location

---

.storybook/main.js
next.config.js
package.json
yarn.lock

Update nextjs to 12.3

---

src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json
src/pages/steps/OrganizerPicker.tsx
src/pages/steps/OrganizerStep.tsx
src/ui/theme.ts

- Make organisator change cta consistent with other components
---
Ticket: https://jira.uitdatabank.be/browse/III-4925

III-4925 - Make organisator change cta consistent with other components

---

.github/CODEOWNERS

- codeowners to enable automatic reviewers

Add codeowners to enable automatic reviewers

---

.github/CODEOWNERS

Fix codeowner file

---

src/pages/steps/OrganizerPicker.tsx

- improve layout of recently used organizer picker
---
Ticket: https://jira.uitdatabank.be/browse/III-4926

III-4926 - improve layout of recently used organizer picker

---

src/hooks/api/events.ts
src/hooks/api/offers.ts
src/hooks/api/organizers.ts
src/hooks/api/places.ts
src/hooks/api/user.ts
src/hooks/useCookiesWithOptions.ts
src/layouts/Sidebar.tsx
src/layouts/index.js
src/pages/dashboard/index.page.tsx
src/pages/steps/OrganizerPicker.tsx
src/utils/getApplicationServerSideProps.js

- Improve security by storing user in memory instead of in a cookie

Improve security by storing user in memory

---

src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json
src/pages/steps/AdditionalInformationStep.tsx
src/pages/steps/BookingInfoStep.tsx

-new  BookingInfoStep
---
Ticket: https://jira.uitdatabank.be/browse/III-5004

III-5004 - New BookingInfoStep

---

src/hooks/api/places.ts
src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json
src/pages/PlaceAddModal.tsx
src/pages/steps/LocationStep.tsx
src/pages/steps/PlaceStep.tsx
src/ui/Input.tsx

- disabled prop to Input component
- `PlaceAddModal` component
---
Ticket: https://jira.uitdatabank.be/browse/III-4860

III-4860 - Modal to enter new location

---

.github/CODEOWNERS
.gitignore
Gemfile
Gemfile.lock
Jenkinsfile
Rakefile
lib/tasks/uitdatabank-frontend/build.rake
lib/tasks/uitdatabank-frontend/build_artifact.rake
lib/tasks/uitdatabank-frontend/prerm
lib/tasks/uitdatabank-frontend/uitdatabank-frontend.service
lib/tasks/uitdatabank-frontend/upstart/uitdatabank-frontend

- New Jenkins pipeline for deploy of udb3-frontend
- .github/codeowners: all Jenkinsfile related stuff to be reviewed by Kristof or Paul
- [Removed ...]
- [Fixed ...]
---

[III-5029] New jenkins pipeline for uitdatabank frontend

---

scripts/README.md
scripts/convert-mapanet-to-udb.mjs

- typo in script
---
Ticket: https://jira.uitdatabank.be/browse/III-4473
I re-ran the scripts on NL and DE, luckily no changes were made.

III-4473 - fix script

---

src/pages/PlaceAddModal.tsx
src/pages/dashboard/index.page.tsx
src/pages/steps/AgeRangeStep.tsx
src/pages/steps/EventTypeAndThemeStep.tsx
src/ui/Button.tsx
src/ui/Dropdown.tsx
src/ui/List.tsx
src/ui/Tabs.tsx
src/ui/theme.ts

- Refinements rounded corners
---
Ticket: https://jira.uitdatabank.be/browse/III-4922

III-4922 - Refinements rounded corners

---

src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json

- Update price info copy
---
Ticket: https://jira.uitdatabank.be/browse/III-5013

III-5013 - Update price info copy

---

src/pages/dashboard/index.page.tsx

-  Fix wrong way to call user query on server
---
Ticket: https://jira.uitdatabank.be/browse/III-5073

III-5073 - Fix wrong way to call user query on server

---

src/ui/Dropdown.tsx

- [Fix rounded corners dropdowns dashboard](https://github.com/cultuurnet/udb3-frontend/commit/99d5f1229bbd7705123569c674930bd96fe43ff9)
---
Ticket: https://jira.uitdatabank.be/browse/III-5037

III-5037 - Fix rounded corners dropdowns dashboard

---

src/pages/PictureUploadBox.tsx
src/pages/VideoUploadBox.tsx
src/pages/steps/AgeRangeStep.tsx
src/pages/steps/EventTypeAndThemeStep.tsx
src/pages/steps/OrganizerPicker.tsx
src/ui/Button.tsx
src/ui/ToggleBox.tsx
src/ui/theme.ts

-  increase contrast secondary buttons
---
Ticket: https://jira.uitdatabank.be/browse/III-5039

III-5039 - increase contrast secondary buttons

---

src/pages/steps/EventTypeAndThemeStep.tsx

Fix check icon color in theme step

---

src/pages/create/EventForm.tsx
src/pages/steps/CalendarStep.tsx
src/ui/Input.tsx
src/ui/Typeahead.tsx

- CalendarStep boilerplate
- basic hour picker for calendar step
---
Ticket: https://jira.uitdatabank.be/browse/III-4472

III-4472 - Set up CalendarStep + add basic hourpicker

---

src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json
src/pages/steps/ScopeStep.tsx

- of in ScopeStep
---
Ticket: https://jira.uitdatabank.be/browse/III-5068

III-5068 - Remove 'of' in ScopeStep

---

src/pages/VideoLinkAddModal.tsx
src/pages/steps/MediaStep.tsx

- `VideoLinkAddModal` reset link to empty string after handleSubmit
- thumbnails for short youtu.be url
---
Ticket: https://jira.uitdatabank.be/browse/III-5076

III-5076 - Fix thumbnails for short youtu.be url

---

src/context/AnnouncementModalContext.tsx
src/layouts/Sidebar.tsx
src/pages/steps/EventScore.tsx

Fix toggle announcements

---

src/pages/OrganizerAddModal.tsx
src/pages/create/EventForm.tsx

- import AdditionalInformation file error

Fix import AdditionalInformation file error

---

src/pages/steps/AdditionalInformationStep/ContactInfoStep.tsx

- [Don't trigger onChangeCompleted if it is undefined](https://github.com/cultuurnet/udb3-frontend/commit/4059fb74157d4ada6fbe43458e9cdccf4c60b587)
---

Don't trigger onChangeCompleted if it is undefined

---

src/pages/steps/AdditionalInformationStep/OrganizerPicker.tsx

-After selecting a "recently used organizer" reset addButtonHasBeenPressed to false 
---
Ticket: https://jira.uitdatabank.be/browse/III-5096

III-5096 - Reset addButtonHasBeenPressed

---

src/pages/steps/AdditionalInformationStep/ContactInfoStep.tsx
src/pages/steps/AdditionalInformationStep/MediaStep.tsx
src/pages/steps/LocationStep.tsx

- Fix cultuurkuur issue on edit
- infinite loop

Fix cultuurkuur issue on edit

---

src/pages/_app.page.js

- hotjar integration
https://nextjs.org/docs/basic-features/script
---
Ticket: https://jira.uitdatabank.be/browse/III-4946

III-4946 - Add hotjar integration

---

src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json
src/pages/steps/AdditionalInformationStep/OrganizerPicker.tsx

- Organisation tab, reorder UI + add info alert
---
Ticket: https://jira.uitdatabank.be/browse/III-5129

III-5129 - Organisation tab, reorder UI + add info alert

---

package.json

Add ci script

---

src/layouts/Sidebar.tsx

- Fix focus from iframe to sidebar

Fix focus from iframe to sidebar

---

src/i18n/nl.json

- Replace Deelname-link by Deelnamelink
---
Ticket: https://jira.uitdatabank.be/browse/III-5137

III-5137 - Replace Deelname-link by Deelnamelink

---

src/pages/dashboard/index.page.tsx
src/pages/steps/ScopeStep.tsx

- scope params to buttons on dashboard
- use scope url param to select scope in `ScopeStep`
---
Ticket: https://jira.uitdatabank.be/browse/III-5080

III-5080 - Add Buttons on dashboard go to corresponding scope

---

src/hooks/api/events.ts
src/pages/manage/movies/MovieForm.tsx
src/pages/steps/AdditionalInformationStep/AdditionalInformationStep.tsx
src/pages/steps/AdditionalInformationStep/OrganizerStep.tsx
src/pages/steps/AdditionalInformationStep/PriceInformation.tsx
src/pages/steps/AudienceStep.tsx
src/pages/steps/PlaceStep.tsx
src/pages/steps/StepsForm.tsx
src/pages/steps/hooks/useAddOffer.ts
src/pages/steps/hooks/useGetEvent.ts
src/pages/steps/hooks/useGetPlace.ts
src/ui/Button.tsx

III-5163 - fix filminvoer crash

---

src/pages/dashboard/index.page.tsx

- Put create offer urls behind feature flag on dashboard

Put create offer urls behind feature flag on dashboard

---

src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json
src/pages/PlaceAddModal.tsx
src/pages/steps/PlaceStep.tsx

- possibility to add zip for NL and DE in `PlaceAddModal`
- error to required zip field in `PlaceAddModal`
- missing terms in addPlaceMutation
---
Ticket: https://jira.uitdatabank.be/browse/III-5179

III-5179 - Fix creation of a new place via PlaceAddModal

---

src/pages/steps/AdditionalInformationStep/BookingInfoStep.tsx

- Reservation period button alignment
---
Ticket: https://jira.uitdatabank.be/browse/III-5176

III-5176 - Reservation period button alignment

---

src/pages/PictureUploadBox.tsx
src/pages/VideoUploadBox.tsx
src/ui/theme.ts

- [Improve styling of media](https://github.com/cultuurnet/udb3-frontend/commit/408e1017177aaadedeae833d2df3ad3952a5c0bf)
---
Ticket: https://jira.uitdatabank.be/browse/III-5153
Screenshot:

III-5153 - Improve styling of media

---

src/pages/events/[eventId]/edit/index.page.tsx

- Redirect to migrate if needed
---
Ticket: https://jira.uitdatabank.be/browse/III-5144

III-5144 - Redirect to migrate if needed

---

src/pages/NewFeatureTooltip.tsx
src/ui/Icon.tsx
src/ui/theme.ts

-  blurry icons NewFeatureTooltip
---
Ticket: https://jira.uitdatabank.be/browse/III-5199

III-5199 - Optimize blurry icons

---

src/pages/steps/AdditionalInformationStep/AdditionalInformationStep.tsx
src/pages/steps/AdditionalInformationStep/OrganizerPicker.tsx

- Increase min height of tab content of additionalInformation
- issue of overflow typeahead of organizers
**Before:**
**After:**
---

III-5200 - Fix overflowing issues in AdditionalInformationStep

---

src/pages/steps/AdditionalInformationStep/OrganizerStep.tsx

- anchor link to #price_info tab in organizer alert
---
Ticket: https://jira.uitdatabank.be/browse/III-5174

III-5174 - Fix anchor link to #price_info tab in organizer alert

---

.github/CODEOWNERS

- Add Emma Fabre to codeowners

Add Emma Fabre to codeowners

---

src/pages/steps/AdditionalInformationStep/AdditionalInformationStep.tsx
src/pages/steps/AdditionalInformationStep/BookingInfoStep.tsx

- optimistic updates to bookingInfo
---
Ticket: https://jira.uitdatabank.be/browse/III-5074

III-5074 - Add optimistic updates to bookingInfo

---

src/pages/steps/AdditionalInformationStep/OrganizerPicker.tsx

- Improve layout of Organizer step
---
Ticket: https://jira.uitdatabank.be/browse/III-5211

III-5211 - Improve layout of Organizer step

---

src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json
src/pages/steps/AdditionalInformationStep/BookingInfoStep.tsx
src/pages/steps/AdditionalInformationStep/ContactInfoStep.tsx

- BookingInfo + ContactInfo: automatically add http:// protocol is user didn't add it
---
Ticket: https://jira.uitdatabank.be/browse/III-5212

III-5212 - BookingInfo + ContactInfo: automatically add http:// protocol is user didn't add it

---

src/pages/steps/CalendarStep/CalendarStep.tsx
src/pages/steps/machines/useCalendarHandlers.tsx

- Use calendarType Permanent by default for Places
---
Ticket: https://jira.uitdatabank.be/browse/III-5222

III-5222 - Use calendarType Permanent by default for Places

---

src/pages/manage/movies/MovieForm.tsx
src/pages/steps/LocationStep.tsx
src/pages/steps/PlaceStep.tsx
src/pages/steps/ProductionStep.tsx
src/pages/steps/hooks/useEditField.ts

- Fix unable to change cinema
---
Ticket: https://jira.uitdatabank.be/browse/III-5223

III-5223 - Fix unable to change cinema

---

src/hooks/api/events.ts

- added missing start & endDate in addEvent payload
---
Ticket: https://jira.uitdatabank.be/browse/III-5233

III-5233 - missing start & endDate in addEvent payload

---

src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json
src/pages/OrganizerAddModal.tsx

- in `OrganizerAddModal`, add possibility to add German address
---
Ticket: https://jira.uitdatabank.be/browse/III-5142

III-5142 -  OrganizerAddModal, add possibility to add German address

---

src/pages/steps/EventTypeAndThemeStep.tsx

- optimistic update on EventTypeAndThemeStep
---
Ticket: https://jira.uitdatabank.be/browse/III-5202

III-5202 - Add optimistic update on EventTypeAndThemeStep

---

src/hooks/api/uitpas.ts
src/pages/steps/AdditionalInformationStep/AdditionalInformationStep.tsx
src/pages/steps/AdditionalInformationStep/OfferScore.tsx
src/pages/steps/AdditionalInformationStep/OrganizerStep.tsx

- Remove cardsystem calls for place
- Calls to events in OfferScore
---
Ticket: https://jira.uitdatabank.be/browse/III-5236

III-5236 - Remove cardsystem calls for place

---

src/pages/steps/EventTypeAndThemeStep.tsx

- Automatically sort types and themes alphabetically
---
Ticket: https://jira.uitdatabank.be/browse/III-5279

Automatically sort types and themes alphabetically

---

src/pages/steps/EventTypeAndThemeStep.tsx

- Add Computer and Techniek to Various Themes
---
Ticket: https://jira.uitdatabank.be/browse/III-5272

Add Computer and Techniek to Various Themes

---

src/pages/steps/AdditionalInformationStep/OrganizerStep.tsx

- Tweak missing price alert for UiTPAS organizers
---
Ticket: https://jira.uitdatabank.be/browse/III-5275

Tweak missing price alert for UiTPAS organizers

---

src/ui/ToggleBox.tsx

- Don't underline the label on active ToggleBox elements
---
Ticket: https://jira.uitdatabank.be/browse/III-5264

Don't underline the label on active ToggleBox elements

---

src/pages/steps/AdditionalInformationStep/AdditionalInformationStep.tsx
src/pages/steps/AdditionalInformationStep/BookingInfoStep.tsx
src/pages/steps/AdditionalInformationStep/ContactInfoStep.tsx
src/pages/steps/AdditionalInformationStep/DescriptionStep.tsx
src/pages/steps/AdditionalInformationStep/MediaStep.tsx
src/pages/steps/AdditionalInformationStep/OrganizerStep.tsx
src/pages/steps/AdditionalInformationStep/PriceInformation.tsx
src/pages/steps/AudienceStep.tsx
src/ui/theme.ts

- Add warning icon on Price tab when empty with UiTPas organizer
- Moved Organiser tab next to Price tab
---
Ticket: https://jira.uitdatabank.be/browse/III-5276

Add warning icon on Price tab when empty with UiTPas organizer

---

src/pages/manage/movies/MovieForm.tsx
src/pages/steps/CalendarStep/CalendarOpeninghoursModal.tsx
src/pages/steps/CalendarStep/CalendarStep.tsx
src/pages/steps/CalendarStep/FixedDays.tsx
src/pages/steps/EventTypeAndThemeStep.tsx
src/pages/steps/LocationStep.tsx
src/pages/steps/NameAndAgeRangeStep.tsx
src/pages/steps/PlaceStep.tsx
src/pages/steps/ProductionStep.tsx
src/pages/steps/ScopeStep.tsx
src/pages/steps/Steps.tsx
src/pages/steps/TimeTableStep.tsx
src/pages/steps/machines/calendarMachine.tsx
src/pages/steps/machines/useCalendarHandlers.tsx

- [Improve typing StepsConfiguration](https://github.com/cultuurnet/udb3-frontend/pull/546/commits/24cd8a7ac8ac29c3ba6780e03bb3be68a9b8bd13)
- [Also update form value calendar on initial load](https://github.com/cultuurnet/udb3-frontend/pull/546/commits/951295cbaaa0f9e9926b83489d3b76d23eb60f97)
- Fix step 3 and 4 disappearing
- [Fix calendar hiding by changing the useFormState so it becomes touched](https://github.com/cultuurnet/udb3-frontend/pull/546/commits/4c7ee778b891ed4b59b6458ebf2dca1aef150cf6)
---
Ticket: https://jira.uitdatabank.be/browse/III-5274

III-5274 - Fix step 3 and 4 disappearing

---

src/pages/steps/AdditionalInformationStep/PriceInformation.tsx

- Fix price validation alert not going away when deleting relevant row
---
Ticket: https://jira.uitdatabank.be/browse/III-5255

Fix price validation alert not going away when deleting relevant row

---

src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json
src/pages/steps/AdditionalInformationStep/OrganizerStep.tsx

- Improve error messages uitpas
---
Ticket: https://jira.uitdatabank.be/browse/III-5263

III-5263 - Improve error messages uitpas

---

src/pages/steps/LocationStep.tsx

- http prefix in LocationStep
---
Ticket: https://jira.uitdatabank.be/browse/III-5248

III-5248 - Fix http prefix in LocationStep

---

src/hooks/api/events.ts

- missing onlineUrl in addEvent payload
---
Ticket: https://jira.uitdatabank.be/browse/III-5249

III-5249 - Fix missing onlineUrl in addEvent payload

---

src/pages/steps/LocationStep.tsx

- [Set audienceType to education when country is undefined](https://github.com/cultuurnet/udb3-frontend/commit/df236908f110234c781faa1d1edd9f23b19f0338)
- set attendanceMode to offline when switching from online / physical location to cultuurkuur location
---
Ticket: https://jira.uitdatabank.be/browse/III-5246

III-5246 - AudienceType education

---

src/hooks/api/places.ts

- missing typicalAgeRange prop in addPlace mutation
---
Ticket: https://jira.uitdatabank.be/browse/III-5295

III-5295 - Add missing typicalAgeRange prop in addPlace mutation

---

src/ui/Box.tsx
src/ui/DatePicker.tsx

- showYearDropdown prop in `DatePicker`
---

III-5312 - Add showYearDropdown prop

---

src/pages/steps/AdditionalInformationStep/PriceInformation.tsx

- Fix Price form failing silently and not saving

Fix Price form failing silently and not saving 

---

src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json
src/pages/create/OfferForm.tsx
src/pages/steps/AdditionalInformationStep/PriceInformation.tsx
src/pages/steps/CalendarStep/CalendarStep.tsx
src/pages/steps/CalendarStep/Days.tsx
src/pages/steps/CalendarStep/OneOrMoreDays.tsx
src/pages/steps/EventTypeAndThemeStep.tsx
src/pages/steps/LocationStep.tsx
src/pages/steps/NameAndAgeRangeStep.tsx
src/pages/steps/ProductionStep.tsx
src/pages/steps/hooks/useEditField.ts

- Validate hours in calendar step
- [Refactor uniqueName validation to use arrow function instead of this …](https://github.com/cultuurnet/udb3-frontend/commit/d44529b753f75b7d5c8591585ca2d493301d65e8)
---
Ticket: https://jira.uitdatabank.be/browse/III-5298

III-5298 - Validate hours in calendar step

---

src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json
src/pages/steps/AdditionalInformationStep/OrganizerPicker.tsx
src/pages/steps/PlaceStep.tsx
src/pages/steps/ProductionStep.tsx

- Update Add New copy of Typeaheads
- Fixed organisation alert overlapping organisation dropdown
---
Ticket: https://jira.uitdatabank.be/browse/III-5242

Update Add New copy of Typeaheads

---

src/pages/steps/AdditionalInformationStep/BookingInfoStep.tsx
src/ui/DatePeriodPicker.tsx

- unnecessary async awaits in  `BookingInfoStep` 
- bug reservation tab: you must select the startdate twice
---
Ticket: https://jira.uitdatabank.be/browse/III-5307

III-5307 - Remove unnecessary async awaits

---

src/pages/steps/LocationStep.tsx
src/pages/steps/ProductionStep.tsx

- [Readd scope](https://github.com/cultuurnet/udb3-frontend/commit/478f352fe4cd49d8a8b6c6422e33ced63d01a1eb)
This was added in another PR but has disappeared, probably because of a merge conflict. 
- [unable to delete onlineUrl](https://github.com/cultuurnet/udb3-frontend/commit/a571ebedd0bae0f908a0ba1cfce5769b6cad7de8)
---
Ticket: https://jira.uitdatabank.be/browse/III-5321

III-5321 - Fix unable to delete onlineUrl

---

src/pages/steps/LocationStep.tsx

- minHeight on locationStep when step5 is not visible
---
Ticket: https://jira.uitdatabank.be/browse/III-5318

III-5318 - Add minHeight on locationStep when step5 is not visible

---

src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json

- Change copy of video links
---
Ticket: https://jira.uitdatabank.be/browse/III-5277

III-5277 - Change copy of video links

---

src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json

- Replace german postal code example
---
Ticket: https://jira.uitdatabank.be/browse/III-5262

III-5262 - Replace german postal code example

---

src/pages/steps/AdditionalInformationStep/AdditionalInformationStep.tsx
src/pages/steps/AdditionalInformationStep/ContactInfoStep.tsx
src/styles/GlobalStyle.js

- Add optimistic updates on ContactInfo tab
Fix contact tab: "jumpy" behaviour:
- ✅  when you add an extra line of contact info (e.g. an extra email address) this new line disappears for a brief time 
- ✅  when you delete a line of contact info the deleted line disappears, then appears again for a brief time
- ✅ when you change the type of contactInfo (e.g. email address --> phone number) the entered data is not cleared. 
- ✅ when you edit an existing line of contact info, the previous contact info for that line appears in the middle of editing that line
---
Ticket: https://jira.uitdatabank.be/browse/III-5294

III-5294 - Fix contact tab: "jumpy" behaviour

---

src/pages/steps/AdditionalInformationStep/BookingInfoStep.tsx
src/pages/steps/AdditionalInformationStep/ContactInfoStep.tsx

- [Don't change startDate || endDate when isDatePickerVisible](https://github.com/cultuurnet/udb3-frontend/commit/920ffd09cca2dfcabe5537a949f254e3886470f2)
- [Fix broken bookingInfo cache on place edit](https://github.com/cultuurnet/udb3-frontend/commit/120e99bc694b2d780b2ef2c776db3b2eeeb406af)
---
Ticket: https://jira.uitdatabank.be/browse/III-5074

III-5074 - Fix validation across fields in the reservation tab

---

src/ui/ToggleBox.tsx
src/ui/theme.ts

- `ToggleBox`  make hover styles consistent
---
Ticket: https://jira.uitdatabank.be/browse/III-5271

III-5271 - ToggleBox make hover styles consistent

---

src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json

- Add UiTPAS reserved name validation message
---
Ticket: https://jira.uitdatabank.be/browse/III-5328

Add UiTPAS reserved name validation message

---

src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json

* Title of step 6
---
Ticket: https://jira.uitdatabank.be/browse/III-5335

Change copy of step 6 title

---

src/pages/create/OfferForm.tsx
src/pages/manage/movies/MovieForm.tsx
src/pages/steps/CalendarStep/CalendarStep.tsx
src/pages/steps/StepsForm.tsx
src/ui/Icon.tsx
src/ui/Toast.stories.mdx
src/ui/Toast.tsx

- Update to more minimalist Toast designs
---
Ticket: https://jira.uitdatabank.be/browse/III-5226

Update to more minimalist Toast designs

---

src/pages/steps/LocationStep.tsx

- Increased minHeight of locationStep container
---
Ticket: https://jira.uitdatabank.be/browse/III-5318

Increased minHeight of locationStep container

---

src/styles/GlobalStyle.js
src/ui/Box.tsx
src/ui/DatePicker.tsx

- Slight datepicker redesign
---
Because there is a broader redesign on the roadmap this is more small design tweaks. Feedback more than welcome since my design days are quite far behind 😅 
Ticket: https://jira.uitdatabank.be/browse/III-5261

Slight datepicker redesign

---

src/pages/steps/LocationStep.tsx

From my local testing the code behaves as is described in the ticket. So I've only made the code structure a bit better and combines some promises.
- Improved code readability
---
Ticket: https://jira.uitdatabank.be/browse/III-5345

III-5345 -  Fix location school audience type

---

src/pages/steps/NameStep.tsx

Small followup fix to https://github.com/cultuurnet/udb3-frontend/pull/608
- Fix name language being undefined when creating new offer
---

Fix name language being undefined when creating new offer

---

src/pages/steps/AgeRangeStep.tsx

- [Account for 0- coming from the backend](https://github.com/cultuurnet/udb3-frontend/commit/04f60379e29693581cb54d695ec1208c25608be8)
---
Ticket: https://jira.uitdatabank.be/browse/III-5253

III-5253 - Improve handling of all ages

---

src/pages/create/OfferForm.tsx

- empty onlineUrl resulting in 400 error
---
Ticket: https://jira.uitdatabank.be/browse/III-5348

III-5348 - Fix empty onlineUrl

---

src/i18n/de.json
src/i18n/fr.json
src/ui/Typeahead.tsx

- [Fix highlight text not showing in dropdown items](https://github.com/cultuurnet/udb3-frontend/commit/0de726f1d367e272a2077ba65e1cfab80c458ff2)
---
Ticket: https://jira.uitdatabank.be/browse/III-5347

III-5347 - Fix highlight text not showing in dropdown items

---

src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json
src/pages/steps/AdditionalInformationStep/AdditionalInformationStep.tsx
src/pages/steps/AdditionalInformationStep/OfferScore.tsx
src/pages/steps/EventTypeAndThemeStep.tsx
src/ui/theme.ts

- Links to tabs in OfferScore
---
Ticket: https://jira.uitdatabank.be/browse/III-5079

III-5079  -  Links to tabs in OfferScore

---

src/pages/steps/AdditionalInformationStep/ContactInfoStep.tsx

- missing onValidationChange in onSuccess of mutation
---
Ticket: https://jira.uitdatabank.be/browse/III-5349

III-5349 - Added missing onValidationChange in onSuccess of mutation

---

src/i18n/de.json
src/i18n/fr.json

-missing FR & DE translations
---
Ticket: https://jira.uitdatabank.be/browse/III-5314

III-5314 - Added missing / fixed missing fr translations

---

src/constants/EventTypes.ts
src/pages/steps/AdditionalInformationStep/OfferScore.tsx
src/pages/steps/CalendarStep/CalendarStep.tsx

- Add extra points for eventtypes without possible themes and Places
---
Ticket: https://jira.uitdatabank.be/browse/III-5344

III-5344 - Add extra points for eventtypes without possible themes and Places

---

src/hooks/useIntersectionObserver.ts
src/pages/steps/AdditionalInformationStep/AdditionalInformationStep.tsx

- [useIntersectionObserver hook](https://github.com/cultuurnet/udb3-frontend/commit/7fd06cc1a4827a973c9d61fb5a8ab77aa3a8bbf4)
https://usehooks-ts.com/react-hook/use-intersection-observer
- [Scroll to AdditionalInformationStep when hash changes and is not already visible on screen](https://github.com/cultuurnet/udb3-frontend/commit/6a38a0f704c215b9c835b967109af3b943ae06b3)
---
Ticket: https://jira.uitdatabank.be/browse/III-5369

III-5369 - OfferScore sroll improvements

---

src/pages/steps/AdditionalInformationStep/AdditionalInformationStep.tsx

- Fix invalidation of queries on /places
---
Ticket: https://jira.uitdatabank.be/browse/III-5377

III-5377 - Fix invalidation of queries on /places

---

src/pages/CityPicker.tsx
src/pages/steps/CalendarStep/CalendarStep.tsx
src/pages/steps/LocationStep.tsx
src/ui/Typeahead.tsx

- [Handle scroll to step 3 (calendar) when there are no possible themes available](https://github.com/cultuurnet/udb3-frontend/commit/1bd02de0de466938db71030e1b51adfd0f42759c)
- [Scroll to CityPicker when focussed in field (only in create flow](https://github.com/cultuurnet/udb3-frontend/pull/624/commits/bd3de4b63a4495e94d1bb674e351142c89651107)
---
Ticket: https://jira.uitdatabank.be/browse/III-5301

III-5301 - Scroll to step improvements

---

src/pages/steps/AdditionalInformationStep/DescriptionStep.tsx
src/pages/steps/AdditionalInformationStep/PriceInformation.tsx

- [Add missing optional chaining on description.length](https://github.com/cultuurnet/udb3-frontend/commit/f438ddddc42e53d240551f49e1ef3d24fe5a53ad)
- [Add logic for onValidationChange on initial load](https://github.com/cultuurnet/udb3-frontend/commit/6a951a00b78d8ea8a3df5fdcf14a9852eea84dfb)
- [Remove hasRates from dep array since it causes the rates to update too soon](https://github.com/cultuurnet/udb3-frontend/commit/c4de6545e868b729061104eee638d78ddb87c2d6)
---
Ticket: https://jira.uitdatabank.be/browse/III-5372

III-5372 - PriceInformation fixes

---

src/pages/steps/AdditionalInformationStep/BookingInfoStep.tsx

- border radius to reservation block
---
Ticket: https://jira.uitdatabank.be/browse/III-5373

III-5373 - Add border radius to reservation block

---

src/pages/steps/AdditionalInformationStep/PriceInformation.tsx

- Fix creating locations crashing on price check
---

Fix creating locations crashing on price check

---

src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json
src/pages/steps/AdditionalInformationStep/AdditionalInformationStep.tsx
src/pages/steps/AdditionalInformationStep/PriceInformation.tsx
src/pages/steps/LocationStep.tsx
src/pages/steps/NameAndAgeRangeStep.tsx
src/pages/steps/Steps.tsx

- Improve flow places address
---
Ticket: https://jira.uitdatabank.be/browse/III-5370

III-5370 -  Improve flow places address

---

src/layouts/Sidebar.tsx
src/pages/NewFeatureTooltip.tsx

- [Make feature help button redirect to /beta-version instead of linking…](https://github.com/cultuurnet/udb3-frontend/commit/ace7e945f87346444f734acda585f469ce25d117)
---
Ticket: https://jira.uitdatabank.be/browse/III-5220

III-5220 - Make feature help button redirect to /beta-version

---

src/constants/EventTypes.ts
src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json
src/pages/steps/EventTypeAndThemeStep.tsx

Reverts cultuurnet/udb3-frontend#638

Revert "Group event types"

---

src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json

The copy of the alert-primary about the suggested organizers so that is applicable on both events and places
---
Ticket: https://jira.uitdatabank.be/browse/III-5396

Correct copy about suggested organizers

---

src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json

"step 5" -> "step 6"
---
Ticket: https://jira.uitdatabank.be/browse/III-5394

Fix reference to incorrect step

---

src/pages/steps/ScopeStep.tsx

- Reset location & calendar after scope change
- Invalid payload error
---
Ticket: https://jira.uitdatabank.be/browse/III-5395

III-5395 - Reset location & calendar after scope change

---

src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json

* Copy for the conversion page
---
Ticket: https://jira.uitdatabank.be/browse/III-5220

Update with final copy

---

src/hooks/api/announcements.ts

- Never include disabled announcements
---
Ticket: https://jira.uitdatabank.be/browse/III-5220

III-5220 - Never include disabled announcements

---

src/pages/steps/AdditionalInformationStep/OrganizerStep.tsx
src/pages/steps/AdditionalInformationStep/PriceInformation.tsx

- [Invalidate offer query after organizer change](https://github.com/cultuurnet/udb3-frontend/commit/c63b48bbb1a670f67710e191e58fcce16de91acf)
- [Only show uitpas price alerts on scope = events](https://github.com/cultuurnet/udb3-frontend/commit/c0f15ff0b5c77b47da1e26d74e8f1a616d3cd3df)
---
Ticket: https://jira.uitdatabank.be/browse/III-5323

III-5323 - UiTPAS prices fixes

---

src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json
src/pages/beta-version.page.tsx

* Removed outro 1
* Made the "old" outro 2 outro 1 now
---
Ticket: https://jira.uitdatabank.be/browse/III-5413

Remove first outro

---

src/pages/steps/PlaceStep.tsx
src/ui/Typeahead.tsx

- [Add customFilter to search on both name and streetAddress](https://github.com/cultuurnet/udb3-frontend/commit/c9be5b93d2bfb5ab0fe352df7989dd6c2bd61dcd)
- [Add highlighter on streetAddress](https://github.com/cultuurnet/udb3-frontend/pull/654/commits/16b0bd5d06b9dc137171b01f51b8c286f92c8e13)
- [Fix labelKey in PlaceStep](https://github.com/cultuurnet/udb3-frontend/commit/ce3cb1d794880e1c20c09937263215653c15446e)
**Screenshot**
---
Ticket: https://jira.uitdatabank.be/browse/III-5416

III-5416 - Fix not all places appear in places drop down in step 4

---

src/pages/steps/hooks/useAddOffer.ts

- `new-entry-form` label when created via new entry form
---
Ticket: https://jira.uitdatabank.be/browse/III-5391

III-5391 - Add `new-entry-form` label on creation of new offer

---

src/pages/steps/AdditionalInformationStep/DescriptionStep.tsx

- Fixed description field getting wider when over 200 characters
---
Ticket: https://jira.uitdatabank.be/browse/III-5404

Fixed description field getting wider when over 200 characters

---

src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json
src/pages/events/[eventId]/edit/index.page.tsx
src/pages/steps/PlaceStep.tsx
src/pages/steps/StepsForm.tsx
src/pages/steps/hooks/useFooterStatus.ts
src/types/Offer.ts

- Port `migrate?location=true` screen to React app
---
Ticket: https://jira.uitdatabank.be/browse/III-5082

Port migrate?location=true screen to React app

---

src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json

- Rename Media tab to Image & Video
---
Ticket: https://jira.uitdatabank.be/browse/III-5420

Rename Media tab to Image & Video

---

src/pages/steps/AdditionalInformationStep/DescriptionStep.tsx

- Fix description not being clearable manually
---
Ticket: https://jira.uitdatabank.be/browse/III-5421

Fix description not being clearable manually

---

src/pages/steps/AdditionalInformationStep/ContactInfoStep.tsx

- Ensure phone numbers don't go over maximum digits
---
Ticket: https://jira.uitdatabank.be/browse/III-5296

Ensure phone numbers don't go over maximum digits

---

src/hooks/api/places.ts

- missing point
---
Ticket: https://jira.uitdatabank.be/browse/III-5432

III-5432 - Added missing point

---

src/hooks/api/places.ts

- quotes around zip to solve issues with dutch zip codes
---
Ticket: https://jira.uitdatabank.be/browse/III-5432

III-5432 - Add quotes around zip to solve issues with dutch zip codes

---

src/pages/steps/AdditionalInformationStep/PriceInformation.tsx

- [Align alerts to the right of PriceInformation if there is room](https://github.com/cultuurnet/udb3-frontend/pull/676/commits/60d61b599cbc5655081649e055944ddd47cb52ed)
---
Ticket: https://jira.uitdatabank.be/browse/III-5313
Screenshots:

III-5313 - Improve alert galore

---

src/pages/VideoLinkAddModal.tsx
src/pages/steps/AdditionalInformationStep/MediaStep.tsx

- [Make convertAllVideoUrlsPromises more readable](https://github.com/cultuurnet/udb3-frontend/commit/ca6f31020db445f8f327834167749b7304935a82)
- [Add support for other url structures](https://github.com/cultuurnet/udb3-frontend/commit/18e071aebf308794b81c52079c5e5eac762ca0de)
- [Fix validation link](https://github.com/cultuurnet/udb3-frontend/pull/682/commits/1bd472acd2e8b4f6e26d7390d5809e150ba25a81)
---
Ticket: https://jira.uitdatabank.be/browse/III-5478
Screenshots:
Event https://io-test.uitdatabank.be/event/ca2f69f1-28df-4f5f-84ce-1837fa929730:
Event https://io.uitdatabank.be/event/5c4f3f23-8708-466e-bcc6-b73447d46569:

III-5478 - Fix vimeo links in edit

---

src/pages/steps/AdditionalInformationStep/OrganizerStep.tsx

- [Fix eventId argument passed to mutation](https://github.com/cultuurnet/udb3-frontend/commit/9320738c34cd1a6eda812653a8674ba13c7e8aaf)
---
Ticket: https://jira.uitdatabank.be/browse/III-5485

III-5485 - Fix cardsystem ui update

---

src/pages/steps/AdditionalInformationStep/OrganizerPicker.tsx

- Stack organizer form sections instead of inline
---
Ticket: https://jira.uitdatabank.be/browse/III-5506

Stack organizer form sections instead of inline

---

src/pages/steps/AdditionalInformationStep/MediaStep.tsx

- Fixed Medias checkmark not disappearing on video deletion
---
https://user-images.githubusercontent.com/1321596/229108623-effb615d-55ed-47f8-8d96-589af81d5782.mp4
---
Ticket: https://jira.uitdatabank.be/browse/III-5483

Fixed Medias checkmark not disappearing on video deletion

---

src/pages/steps/ScopeStep.tsx

- Fix scope not being reset when navigating to fresh entry form
---
Ticket: https://jira.uitdatabank.be/browse/III-5427

Fix scope not being reset when navigating to fresh entry form

---

src/pages/steps/CalendarStep/CalendarStep.tsx

- Fixed Calendar state being refreshed when changing unrelated fields on the Offer and triggering toast message
---
Ticket: https://jira.uitdatabank.be/browse/III-5502

Fixed Calendar state being refreshed when changing unrelated fields on the Offer

---

src/hooks/api/organizers.ts
src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json
src/pages/OrganizerAddModal.tsx
src/pages/steps/AdditionalInformationStep/OrganizerStep.tsx
src/ui/Box.tsx

- Added prompt to select existing organizer when new origanizer URL is already assigned to one
- Fixed address being mandatory in Add Organizer modal
---
@corneelwille Will need a peek at those translations since I've used Google to fill the DE/NL ones for now
https://user-images.githubusercontent.com/1321596/230048070-62eefedf-9cc9-4c46-94a7-cf5807f3c90d.mp4
Ticket: https://jira.uitdatabank.be/browse/III-5518

Changes to Add Organizer modal

---

src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json
src/pages/create/OfferForm.tsx
src/pages/dashboard/index.page.tsx
src/pages/manage/movies/MovieForm.tsx
src/types/WorkflowStatus.ts

- Improve status badge dashboard
---
Ticket: https://jira.uitdatabank.be/browse/III-5380

III-5380 - Improve status badge dashboard

---

src/i18n/fr.json

- Add missing spaces in french punctuation
---
Ticket: https://jira.uitdatabank.be/browse/III-5292

Add missing spaces in french punctuation

---

src/hooks/api/labels.ts
src/hooks/api/offers.ts
src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json
src/pages/steps/AdditionalInformationStep/AdditionalInformationStep.tsx
src/pages/steps/AdditionalInformationStep/BookingInfoStep.tsx
src/pages/steps/AdditionalInformationStep/ContactInfoStep.tsx
src/pages/steps/AdditionalInformationStep/DescriptionStep.tsx
src/pages/steps/AdditionalInformationStep/LabelsStep.tsx
src/pages/steps/AdditionalInformationStep/MediaStep.tsx
src/pages/steps/AdditionalInformationStep/OfferScore.tsx
src/pages/steps/AdditionalInformationStep/OrganizerStep.tsx
src/pages/steps/AdditionalInformationStep/PriceInformation.tsx
src/pages/steps/CalendarStep/CalendarStep.tsx
src/pages/steps/LocationStep.tsx
src/types/Offer.ts

- Add Labels management to entry form
- [internal] Added `useGetOfferByIdQuery` to simplify getting offer based on scope
---
https://user-images.githubusercontent.com/1321596/230424368-2e1cc369-08b9-4435-a6db-108d6778e314.mp4
---
Ticket: https://jira.uitdatabank.be/browse/III-5267

Add Labels management to entry form

---

src/pages/steps/AdditionalInformationStep/OrganizerPicker.tsx
src/pages/steps/LocationStep.tsx
src/ui/ButtonCard.tsx

- Suggested locations in step 4: small improvements
---
Ticket: https://jira.uitdatabank.be/browse/III-5568

III-5568 - Suggested locations in step 4: small improvements

---

src/pages/steps/AdditionalInformationStep/DescriptionStep.tsx
src/styles/GlobalStyle.js

- Make Description field layout properly wrap
---
Also made it stack on L instead of M since M meant the field would get uncomfortably shrunk for a while before stacking.
https://user-images.githubusercontent.com/1321596/233970416-4223102b-f9f0-4082-b007-1c0c36a03341.mp4
Ticket: https://jira.uitdatabank.be/browse/III-5404

Make Description field layout properly wrap

---

src/pages/steps/AdditionalInformationStep/ContactInfoStep.tsx

- Allow - in phone numbers
---
Ticket: https://jira.uitdatabank.be/browse/III-5296

Allow - in phone numbers

---

src/pages/steps/LocationStep.tsx
src/ui/ButtonCard.tsx

- Added vertical margin between city and street
- Don't show Recent Locations on Online/School offers
- Fixed more than 4 recent locations showing up
- Fixed recent location titles not using whole width
---
Ticket: https://jira.uitdatabank.be/browse/III-5571

Tweaks to Location step

---

src/pages/steps/AdditionalInformationStep/OrganizerStep.tsx

- Make card systems UI optimistic
---
https://user-images.githubusercontent.com/1321596/234613771-86bd5eb5-4d97-4f05-87bf-a69db6c03833.mp4
Ticket: https://jira.uitdatabank.be/browse/III-5501

Make card systems UI optimistic

---

src/pages/RichTextEditor.tsx
src/pages/steps/AdditionalInformationStep/DescriptionStep.tsx

- Use soft newlines when pressing "Enter"
- Make editor as tall as previous description field
- Make editor resizable in height
- Removed "underline" option
---
Ticket: https://jira.uitdatabank.be/browse/III-5115

Tweaks to rich text editor

---

src/i18n/nl.json

- NL copy of the alert info when "location in consultation with the school" is selected
---
Ticket: https://jira.uitdatabank.be/browse/III-5587

III-5587 new copy bookable school events

---

src/pages/create/OfferForm.tsx
src/pages/steps/StepsForm.tsx

- unused imports in `OfferForm`
- Fix wrong attendanceMode `Offline` when duplicating an online event
---
Ticket: https://jira.uitdatabank.be/browse/III-5081

III-5081 - Fix wrong attendanceMode when duplicating an online event

---

src/pages/steps/AdditionalInformationStep/OrganizerStep.tsx

- Don't show uitpas alert when there are no active cardsystems
---
Ticket: https://jira.uitdatabank.be/browse/III-5561

III-5561 - Don't show uitpas alert when there are no active cardsystems

---

src/hooks/api/offers.ts
src/hooks/api/places.ts
src/pages/places/[placeId]/availability.page.js
src/pages/steps/hooks/useGetPlace.ts

- unnecessary call to /places on event detail page
---
Ticket: https://jira.uitdatabank.be/browse/III-5602

III-5602 - Fix unnecessary call to /places on event detail page

---

src/pages/steps/AdditionalInformationStep/PriceInformation.tsx

- Improve layout of alerts on PriceInformation on smaller screens.
---
Ticket: https://jira.uitdatabank.be/browse/III-5313

III-5313 - Improve layout of alerts on PriceInformation

---

src/layouts/Sidebar.tsx
src/pages/login/[language].page.tsx

- [Change router.push to location.assign for /api/auth/ routes](https://github.com/cultuurnet/udb3-frontend/commit/c870ab1df408c47ae0bb989676b568e40f8bb98d)
- Fix auth0 login flow
---
Ticket: https://jira.uitdatabank.be/browse/III-5285

III-5285 - Fix auth0 login flow

---

src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json
src/pages/steps/AudienceStep.tsx

- Add help text to Audience step
---
Ticket: https://jira.uitdatabank.be/browse/III-5588

Add help text to Audience step

---

.github/workflows/e2e.yml
src/hooks/api/events.ts
src/hooks/api/offers.ts
src/hooks/api/organizers.ts
src/hooks/api/places.ts
src/hooks/api/user.ts
src/layouts/Sidebar.tsx
src/pages/dashboard/index.page.tsx
src/pages/events/[eventId]/availability.multiple.test.js
src/pages/events/[eventId]/availability.single.test.js
src/pages/places/[placeId]/availability.test.js
src/test/e2e/auth.spec.ts
src/test/e2e/setup/auth.setup.ts
src/types/User.ts
src/utils/fetchFromApi.ts

- call the the `/userinfo` endpoint from auth0 directly
- User type
- `fetchFromApi` to be able to accept a different `apiUrl`
- Use the first name and picture from auth0
---
Ticket: https://jira.uitdatabank.be/browse/III-5573

III-5573  - Show firstName instead username

---

src/pages/RichTextEditor.tsx
src/styles/GlobalStyle.js

- Tweak styling of RTE to be more in line with rest
---
Ticket: https://jira.uitdatabank.be/browse/III-5633

Tweak styling of RTE to be more in line with rest

---

src/pages/create/OfferForm.tsx
src/pages/steps/LocationStep.tsx

-  Don't send audienceType in the payload on events which have a location "in overleg met de school"
---
Ticket: https://jira.uitdatabank.be/browse/III-5539

III-5539 - Don't set audienceType on 'educational' events

---

src/pages/steps/LocationStep.tsx

- Only show onlineToggle & recentLocations when scope = Events
---
Ticket: https://jira.uitdatabank.be/browse/III-5644

III-5644 - Only show onlineToggle & recentLocations when scope = Events

---

src/hooks/api/authenticated-query.ts

- Temporary disable caching on priceInfo mutations
---
Ticket: https://jira.uitdatabank.be/browse/III-5620

III-5620 - Temporary disable caching on priceInfo mutations

---

src/pages/steps/AdditionalInformationStep/PriceInformation.tsx

- Decrease width of priceInformation block
---
Ticket: https://jira.uitdatabank.be/browse/III-5313

III-5313 - Decrease width of priceInformation block

---

src/pages/steps/AdditionalInformationStep/OrganizerPicker.tsx

- `OrganizerPicker` Improve size for screens with smaller resolutions
---
Ticket: https://jira.uitdatabank.be/browse/III-5610

III-5610 - OrganizerPicker Improve size for screens with smaller resolutions

---

src/hooks/api/events.ts
src/hooks/api/organizers.ts
src/hooks/api/places.ts
src/pages/dashboard/index.page.tsx

- Fetch offers and organizers with uitidv1 as well
---
Ticket: https://jira.uitdatabank.be/browse/III-5650

III-5650 - Fetch offers and organizers with uitidv1 as well

---

src/pages/steps/AudienceStep.tsx

- Only show help text for education audience
---
Ticket: https://jira.uitdatabank.be/browse/III-5588

Only show help text for education audience

---

src/pages/dashboard/index.page.tsx

- Don't show eventType in description on Dashboard if undefined
---
Ticket: https://jira.uitdatabank.be/browse/III-5659

III-5659 - Don't show eventType in description if undefined

---

src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json
src/pages/steps/AdditionalInformationStep/OrganizerPicker.tsx

- [maxWidth to OrganizerTypeAhead](https://github.com/cultuurnet/udb3-frontend/commit/219a3e339dd053025e9f184842e9e8eded4b5338)
- [copy for adding/ using recent organizers](https://github.com/cultuurnet/udb3-frontend/commit/102822ff38aee51e54864f40a8fac1229efc8557)
---
Ticket: https://jira.uitdatabank.be/browse/III-5658

III-5658 - Improvements for users that do not have "suggested organizers"

---

src/hooks/api/events.ts
src/hooks/api/organizers.ts
src/hooks/api/places.ts

- Omit Authorization headers from dashboard api calls
---
Ticket: https://jira.uitdatabank.be/browse/III-5663

III-5663 - Omit Authorization headers from dashboard api calls

---

src/pages/steps/LocationStep.tsx
src/pages/steps/PlaceStep.tsx

- error when selecting location in MovieForm
---
Ticket: https://jira.uitdatabank.be/browse/III-5686

III-5686 - Fix error when selecting location in MovieForm

---

src/pages/steps/AdditionalInformationStep/LabelsStep.tsx

- Modify regex to allow whitespaces in labels
---
Ticket: https://jira.uitdatabank.be/browse/III-5695

III-5695 - Modify regex to allow whitespaces in labels

---

src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json

- missing tip text for booking_info
---
Ticket: https://jira.uitdatabank.be/browse/III-5691

III-5691 - Add missing tip text for booking_info

---

src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json
src/pages/steps/AdditionalInformationStep/ContactInfoStep.tsx

- allow `!` in url regex
---
Ticket: https://jira.uitdatabank.be/browse/III-5697

III-5697 - Also allow ! in url's

---

src/pages/steps/CalendarStep/Days.tsx

- Closes #765 
---
Ticket: https://jira.uitdatabank.be/browse/III-5700

III-5700 - Fix duplicate page crashing when reason is undefined

---

src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json
src/pages/dashboard/index.page.tsx

- duplicate link to actions on dashboard
---
Ticket: https://jira.uitdatabank.be/browse/III-5702

III-5702 - Add duplicate link to actions on dashboard

---

src/test/e2e/events/create-online-location.spec.ts

- E2E test for event with online location
---
Ticket: https://jira.uitdatabank.be/browse/III-5716

III-5716 - Add E2E test for event with online location

---

src/test/e2e/events/create-calendar-periodic.spec.ts

- E2E test for creation of event with calendar type periodic + openingHours
---
Ticket: https://jira.uitdatabank.be/browse/III-5715

III-5715 - Add test for creation of event with calendar type periodic

---

src/test/e2e/events/create-calendar-multiple.spec.ts

- E2E test for creation of an event with calendarType multiple
---
Ticket: https://jira.uitdatabank.be/browse/III-5713

III-5713 - Add e2e test for creation of an event with calendarType multiple

---

src/test/e2e/events/create-calendar-single.spec.ts

- E2E test for creation of an event with CalendarType single
---
Ticket: https://jira.uitdatabank.be/browse/III-5711

III-5711 - Add spec for create event with calendarType single

---

src/pages/steps/LocationStep.tsx

- Fix unsafe access to localized address in LocationStep
---
Ticket: https://jira.uitdatabank.be/browse/III-5668

Fix unsafe access to localized address in LocationStep

---

src/pages/steps/AdditionalInformationStep/OrganizerStep.tsx

- Catch ticket sales error and show relevant message
---
https://github.com/cultuurnet/udb3-frontend/assets/1321596/9e415e99-357f-44e4-b7b0-198b6d8a724c
Ticket: https://jira.uitdatabank.be/browse/III-5507

Catch ticket sales error and show relevant message

---

src/test/e2e/events/create-uitpas-event.spec.ts

- E2E test for uitpas event
---
Ticket: https://jira.uitdatabank.be/browse/III-5720

III-5720 - Add E2E test for uitpas event

---

src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json

- Fix missing updated translations for Uitpas ticket sales error
---
🤦‍♀️ 
Ticket: https://jira.uitdatabank.be/browse/III-5507

Fix missing updated translations for Uitpas ticket sales error

---

src/test/e2e/events/duplicate-event.spec.ts

- E2E test for duplication of event
---
Ticket: https://jira.uitdatabank.be/browse/III-5727

III-5727 - Add E2E test for duplication of event

---

src/pages/steps/CountryPicker.tsx
src/test/e2e/events/create-bookable-school-event.spec.ts

- E2E test for bookable school event
---
Ticket: https://jira.uitdatabank.be/browse/III-5724

III-5724 -  E2E test for bookable school event

---

src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json
src/pages/OrganizerAddModal.tsx
src/pages/create/OfferForm.tsx
src/pages/steps/LocationStep.tsx

-  Field to fill in postalCode on location when Country is NL or DE
---
Ticket: https://jira.uitdatabank.be/browse/III-5718

III-5718 - Add postalCode field on create place (when country is NL or DE)

---

.github/workflows/e2e.yml
playwright.config.ts
src/pages/steps/AdditionalInformationStep/OfferScore.tsx
src/test/e2e/create-place.spec.ts
src/test/e2e/events/create-full-event.spec.ts

- E2E test for creation of event with all fields filled in
---
Ticket: https://jira.uitdatabank.be/browse/III-5726

III-5726 - E2E test for creation of event with all fields filled in

---

src/constants/OfferType.ts
src/hooks/api/offers.ts
src/hooks/api/organizers.ts
src/hooks/api/terms.ts
src/pages/create/OfferForm.tsx
src/pages/dashboard/index.page.tsx
src/pages/organizers/create/OrganizerForm.tsx
src/pages/steps/AdditionalInformationStep/AdditionalInformationStep.tsx
src/pages/steps/AdditionalInformationStep/ContactInfoStep.tsx
src/pages/steps/AdditionalInformationStep/LabelsStep.tsx
src/pages/steps/LocationStep.tsx
src/pages/steps/Steps.tsx

- Add Contact Information step to organizer form
---
Ticket: https://jira.uitdatabank.be/browse/III-4494

Add Contact Information step to organizer form

---

src/pages/steps/AdditionalInformationStep/LabelsStep.tsx

- Add labels step to organizer form
---
Ticket: https://jira.uitdatabank.be/browse/III-5678

Add labels step to organizer form

---

src/hooks/api/offers.ts
src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json
src/pages/PictureUploadBox.tsx
src/pages/steps/AdditionalInformationStep/AdditionalInformationStep.tsx
src/pages/steps/AdditionalInformationStep/FormScore.tsx
src/pages/steps/AdditionalInformationStep/MediaStep.tsx
src/types/Organizer.ts

- Add images step to organizer form
---
Ticket: https://jira.uitdatabank.be/browse/III-5676

Add images step to organizer form

---

src/pages/steps/AdditionalInformationStep/BookingInfoStep.tsx
src/pages/steps/AdditionalInformationStep/ContactInfoStep.test.js
src/pages/steps/AdditionalInformationStep/ContactInfoStep.tsx
src/pages/steps/LocationStep.tsx
src/utils/isValidInfo.ts

- Fixed .vlaanderen URLs failing validation
---
Ticket: https://jira.uitdatabank.be/browse/III-5735

Fixed .vlaanderen URLs failing validation

---

README.md

- `README.md`: added info about how to connect to [udb3-backend](https://github.com/cultuurnet/udb3-backend) with `Docker`.
---
Ticket: https://jira.uitdatabank.be/browse/III-5770

III-5770 Add info about running it with docker

---

src/ui/Pagination.tsx

- Update dashboard pagination border radii
---
Ticket: https://jira.uitdatabank.be/browse/III-5092

Update dashboard pagination border radii

---

src/pages/steps/AdditionalInformationStep/LabelsStep.tsx

- Allow common accented letters in labels
---
Ticket: https://jira.uitdatabank.be/browse/III-5768

Allow common accented letters in labels

---

src/layouts/Sidebar.tsx
src/pages/dashboard/index.page.tsx

- Add Delete button to organizers dashboard
---
Ticket: https://jira.uitdatabank.be/browse/III-4960

Add Delete button to organizers dashboard

---

src/hooks/useHandleWindowMessage.js
src/layouts/Sidebar.tsx

- Refetch moderation count query on Moderated message
---
Requires https://github.com/cultuurnet/udb3-angular/pull/757
---
Ticket: https://jira.uitdatabank.be/browse/III-5486

Refetch moderation count query on Moderated message

---

src/pages/steps/AdditionalInformationStep/ContactInfoStep.test.js
src/utils/isValidInfo.ts

- [test case in isValidUrl test](https://github.com/cultuurnet/udb3-frontend/commit/b8f8ec323c4878861129d6073c1ebc530a518ee4)
- [extra regex for validation of TLD in urls](https://github.com/cultuurnet/udb3-frontend/commit/42bb963b49bf7f88e333a72d2a5c30f53c497450)
---
Ticket: https://jira.uitdatabank.be/browse/III-5847

III-5847 - Add extra regex for validation of TLD in urls

---

src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json
src/pages/steps/AgeRangeStep.tsx
src/pages/steps/NameAndAgeRangeStep.tsx
src/ui/Input.tsx

- [numeric input type](https://github.com/cultuurnet/udb3-frontend/commit/3eecd1b0a6ab7f51dde4f60a3b205c7b2313f003)
- [Handle validation for custom age ranges](https://github.com/cultuurnet/udb3-frontend/commit/26f31147c512c0a5fb8b0504e354c16ce3a24a8f)
---
Ticket: https://jira.uitdatabank.be/browse/III-5817

III-5817 - Handle validation for custom age ranges

---

src/pages/organizers/create/OrganizerForm.tsx

- Also use hiddenLabels for showing cultuurkuur tab on organiser
---
Ticket: https://jira.uitdatabank.be/browse/III-5746

III-5746 - Also use hiddenLabels for showing cultuurkuur tab on organiser

---

src/pages/steps/AdditionalInformationStep/AdditionalInformationStep.tsx

- scroll to additionalInformationStep on OrganizersForm
---
Ticket: https://jira.uitdatabank.be/browse/III-5848

III-5848 - Add scroll to additionalInformationStep on OrganizersForm

---

src/pages/organizers/create/steps/UrlStep.tsx

- url validation in step1 of Organizer Form
---
Ticket: https://jira.uitdatabank.be/browse/III-5847

III-5847 - Add url validation in step1 of Organizer Form

---

src/pages/steps/AdditionalInformationStep/PhysicalLocationStep.tsx

- Do not add validation marker to organizer location step
---
Ticket: https://jira.publiq.be/browse/III-5843

Do not add validation marker to organizer location step

---

src/pages/steps/AdditionalInformationStep/MediaStep.test.js
src/pages/steps/AdditionalInformationStep/MediaStep.tsx

- Fixed Youtube Shorts thumbnails
- Fixed shortened Youtube URLs thumbnails
---
There was a slight bug in the code that made shortened URLs with query parameters not extract the ID properly. I've unified it all to one regex and path also so the thumbnail URLs are all consistent.
Ticket: https://jira.publiq.be/browse/III-5850

Fixed Youtube Shorts and shortened URLs thumbnails

---

src/hooks/useDebounce.tsx
src/pages/organizers/create/steps/UrlStep.tsx

- [useDebounce hook](https://github.com/cultuurnet/udb3-frontend/commit/2f16ca74494a6d7d1d7206f2cf3a812bb0d1d91c)
- Validation on website url in step 1 is sometimes slow
---
Ticket: https://jira.uitdatabank.be/browse/III-5846

III-5846 - use debounced value for getOrganizersByWebsiteQuery

---

src/pages/organizers/create/steps/UrlStep.tsx

- Also prefix searchInput with https onBlur
---
Ticket: https://jira.uitdatabank.be/browse/III-5846

III-5846 - Also prefix searchInput with https onBlur

---

src/pages/RichTextEditor.tsx

- Allow RTE to grow in height instead of hiding extra content
---
Ticket: https://jira.publiq.be/browse/III-5864

Allow RTE to grow in height instead of hiding extra content

---

src/pages/organizers/create/OrganizerForm.tsx
src/pages/steps/AdditionalInformationStep/LabelsStep.tsx
src/utils/getUniqueLabels.ts

- Ensure hidden labels are also present in LabelsStep
---
Ticket: https://jira.publiq.be/browse/III-5865

Ensure hidden labels are also present in LabelsStep

---

src/styles/GlobalStyle.js

- Reduce RTE margins more
---
cc @corneelwille 
Ticket: https://jira.publiq.be/browse/III-5866

Reduce RTE margins more

---

src/hooks/api/authenticated-query.ts

- offers change calendar 
---
Ticket: https://jira.uitdatabank.be/browse/III-5877

III-5877 - Fix offers change calendar not working due to caching mechanism

---

src/pages/organizers/create/steps/UrlStep.tsx

- Fixed "Valid URL" message checking if form is dirty instead of URL
- Fixed "Valid URL" message showing briefly until uniqueness check comes back
---
Ticket: https://jira.publiq.be/browse/III-5858

Fixed some URL validation behaviors

---

src/hooks/api/offers.ts

- Fixed inability to update existing organiser images
---
Ticket: https://jira.publiq.be/browse/III-5873

Fixed inability to update existing organiser images

---

src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json

- alert primary copy for labels
---
Ticket: https://jira.uitdatabank.be/browse/III-5870

Add info about spaces being allowed

---

src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json

- copy for "website" in the reservation tab
---
Ticket: https://jira.uitdatabank.be/browse/III-5894

Change copy for "website" in reservation tab

---

src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json
src/pages/steps/AdditionalInformationStep/OrganizerStep.tsx

- action for when uitpas organizer was not found
---
Ticket: https://jira.uitdatabank.be/browse/III-5672

III-5672 - Add action for when uitpas organizer was not found

---

src/hooks/api/organizers.ts
src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json
src/pages/organizers/create/OrganizerForm.tsx
src/pages/organizers/create/steps/UrlStep.tsx
src/pages/steps/Steps.tsx
src/test/e2e/create-organizer.spec.ts
src/ui/Box.tsx
src/ui/FormElement.tsx
src/ui/Label.tsx

- Added ability to reuse organizer URL as contact
---
Ticket: https://jira.publiq.be/browse/III-5878

Added ability to reuse organizer URL as contact

---

src/i18n/nl.json

- Copy for video upload
---
Ticket: https://jira.uitdatabank.be/browse/III-5911

Improve NL copy video upload

---

src/pages/OrganizerAddModal.tsx
src/pages/steps/AdditionalInformationStep/ContactInfoStep.tsx

- Added Contact URL toggle to new organizer modal
---
https://github.com/cultuurnet/udb3-frontend/assets/1321596/2e7a3aa4-a2d9-4606-830b-55f1f2f0ab67
Ticket: https://jira.publiq.be/browse/III-5879

Added Contact URL toggle to new organizer modal

---

src/pages/OrganizerAddModal.tsx
src/pages/organizers/create/steps/UrlStep.tsx

- Fixed labels of "Is contact URL?" field being bold
---
Ticket: https://jira.publiq.be/browse/III-5906

Fixed labels of "Is contact URL?" field being bold

---

src/pages/RichTextEditor.tsx
src/styles/GlobalStyle.js
src/test/e2e/create-place.spec.ts
src/test/e2e/events/create-full-event.spec.ts

- Added ability to use hyperlinks in descriptions
---
https://github.com/cultuurnet/udb3-frontend/assets/1321596/93c9edfa-bc1b-4de9-8924-0f81aa777d5c
Ticket: https://jira.publiq.be/browse/III-5893

Added link feature to RTEs

---

src/hooks/api/offers.ts
src/hooks/api/organizers.ts
src/pages/steps/AdditionalInformationStep/DescriptionStep.tsx

- Fixed inability to clear organizer descriptions
---
Also updated the offer code to use a DELETE so it's more uniform, since the PUT way is the older way.
Ticket: https://jira.publiq.be/browse/III-5868

Fixed inability to clear organizer descriptions

---

src/pages/steps/LocationStep.tsx

- zipcode next to municipality instead of address
- [III-5931 - Fix wrong zip](https://github.com/cultuurnet/udb3-frontend/pull/851/commits/22e72c1d4ca1047270b8b28f3730103bbe59ac07)
---
Tickets: 
https://jira.uitdatabank.be/browse/III-5928
https://jira.publiq.be/browse/III-5931

III-5928 - Show zipcode next to municipality instead of address

---

src/pages/AvailabilityPageMultiple.tsx
src/pages/AvailabilityPageSingle.tsx
src/pages/steps/AdditionalInformationStep/MediaStep.tsx
src/pages/steps/CountryPicker.tsx
src/pages/steps/LocationStep.tsx
src/pages/steps/ScopeStep.tsx
src/ui/Button.tsx
src/ui/CustomIcon.tsx
src/ui/SelectionTable.js
src/ui/theme.ts

- Layout improvements
---
Ticket: https://jira.uitdatabank.be/browse/III-5851

III-5851 -  follow up

---

src/ui/DatePeriodPicker.tsx

- wrong endDate (when you selected a startDate which was after the endDate)
---
Ticket: https://jira.uitdatabank.be/browse/III-5861

III-5861 - Fix wrong endDate

---

src/layouts/Sidebar.tsx
src/pages/dashboard/index.page.tsx
src/redirects.tsx

- Make new entry form the default
- Redirects to old entry form
---
Ticket: https://jira.uitdatabank.be/browse/III-5418

III-5418 - Make new entry form the default

---

src/pages/dashboard/index.page.tsx
src/redirects.tsx

Fix organizer routes

---

src/i18n/nl.json

- copy publication channels
---
Ticket: https://jira.uitdatabank.be/browse/III-5940

Include UiTinVlaanderen in copy about publication channels

---

.github/CODEOWNERS

- Remove Hanne Sips from CODEOWNERS

Remove Hanne Sips from CODEOWNERS

---

src/pages/login/[language].page.tsx

- Fixed Login button sometimes bieng covered on small viewports
---
https://github.com/cultuurnet/udb3-frontend/assets/1321596/e2abfd9b-9245-4930-9b2e-78e5d2134e45
Ticket: https://jira.publiq.be/browse/III-5939

Fixed Login button sometimes bieng covered on small viewports

---

src/layouts/Sidebar.tsx

- Possibility to scroll in sidebar with lots of items
---
Ticket: https://jira.publiq.be/browse/III-5941

III-5941 - Possibility to scroll in sidebar with lots of items

---

src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json
src/pages/steps/AdditionalInformationStep/OrganizerStep.tsx

- Make a non selectable option for the distribution key dropdown
---
Ticket: https://jira.uitdatabank.be/browse/III-5915

III-5915 - Make a non selectable option for the distribution key dropdown

---

src/layouts/Sidebar.tsx

- [Hotjar try using window instead of Hotjar event](https://github.com/cultuurnet/udb3-frontend/commit/789729fe265a58d81eae22c1dbe90ff498085590)
- [Don't do a router replace for now](https://github.com/cultuurnet/udb3-frontend/commit/a873717017e2f3e6e16cfed2cd5f62333f3c1486)
---
Ticket: https://jira.uitdatabank.be/browse/III-5882

III-5882 - Hotjar survey trigger

---

src/layouts/Sidebar.tsx

Ticket: https://jira.uitdatabank.be/browse/III-5882

III-5882 - Hotjar survey implementation when no image

---

src/layouts/Sidebar.tsx

Ticket: https://jira.uitdatabank.be/browse/III-5882

III-5882 - Add extra early return

---

src/hooks/api/organizers.ts
src/pages/organizers/create/OrganizerForm.tsx

- Prevent losing organizer data when updating name or URL. Fixed by using granular endpoints.
---
Ticket: https://jira.uitdatabank.be/browse/III-5958

III-5958 Fix organizer update

---

src/pages/login/[language].page.tsx

- HomeIllustration: arrows being covered by UDBCard
---
Ticket: https://jira.uitdatabank.be/browse/III-5949

III-5949 - Fix arrows being covered by UDBCard

---

src/pages/VideoUploadBox.tsx
src/pages/steps/AdditionalInformationStep/FormScore.tsx
src/pages/steps/AdditionalInformationStep/OrganizerPicker.tsx
src/pages/steps/LocationStep.tsx

- Remove all New Feature Tooltips related to the new entry forms
---
Ticket: https://jira.publiq.be/browse/III-5913

Remove all New Feature Tooltips related to the new entry forms

---

src/pages/steps/CalendarStep/Days.tsx
src/ui/DatePeriodPicker.tsx

- Allow picking dates in the past in Datepicker
---
Ticket: https://jira.publiq.be/browse/III-5967

Allow picking dates in the past in Datepicker

---

src/pages/PlaceAddModal.tsx

- [Change button variant style of categories in PlaceAddModal](https://github.com/cultuurnet/udb3-frontend/commit/f401b91a1a94ba3f5eec750b402854a90cb85dbb)
---
Ticket: https://jira.publiq.be/browse/III-5988

III-5988 - Change button variant style of categories in PlaceAddModal

---

src/hooks/api/authenticated-query.ts
src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json
src/pages/AlertDuplicatePlace.tsx
src/pages/PlaceAddModal.tsx
src/utils/fetchFromApi.ts

- [warning messages for duplicate_place in add_modal](https://github.com/cultuurnet/udb3-frontend/commit/63ce9cbd23a12f1f20154d3573156ee3c2b855c2)
- [FetchError to include optional error response body](https://github.com/cultuurnet/udb3-frontend/commit/cd6d296894eccc44f6121a5cc857d70dc3fccb9e)
- [always execute places-add mutation (even with duplicate payload)](https://github.com/cultuurnet/udb3-frontend/commit/2b8c1125417b5d9bc7f688ff30cee893bf0636df)
- [Show Warning Alert if duplicate place](https://github.com/cultuurnet/udb3-frontend/commit/2938575956f6c12dc47a9834bf3014b92bdd93ec)
---
Ticket: https://jira.uitdatabank.be/browse/III-6000

III-6000 - Show warning message if duplicate place in PlaceAddModal

---

src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json
src/pages/steps/NameAndAgeRangeStep.tsx
src/pages/steps/Steps.tsx
src/pages/steps/StepsForm.tsx
src/pages/steps/hooks/useAddOffer.ts

- [errors to StepsProps](https://github.com/cultuurnet/udb3-frontend/commit/e8fb85e713d547e12b255ee713f50348766a97c0)
- [duplicate_place error labels](https://github.com/cultuurnet/udb3-frontend/commit/8e9e38dde11169fb47ae6737a1b5c062b39b460a)
- [errors to Steps](https://github.com/cultuurnet/udb3-frontend/commit/dc0093381012c352f4a0f469617b5b334e56fece)
- [Show AlertDuplicatePlace on duplicate fetch error](https://github.com/cultuurnet/udb3-frontend/commit/5d04626eaf030d0ec802f2a1b98e940667cda4ec)
- [Catch error in useAddOffer](https://github.com/cultuurnet/udb3-frontend/commit/f25296f55aa9d7db07f38a7fbcebdd5c9fe69d8b)
Screenshots:
---
Ticket: https://jira.publiq.be/browse/III-6001

III-6001 - direct user to originalPlace when trying to create an identical place

---

src/pages/AlertDuplicatePlace.tsx
src/pages/PlaceAddModal.tsx

- [parseOfferId when placeId is defined](https://github.com/cultuurnet/udb3-frontend/commit/b494369e2d61ab588964bece39f39feded3955df)
- [unused imports](https://github.com/cultuurnet/udb3-frontend/commit/ee791ec653397a357c8e9e7ca2395445fb20c6e8)
---
Ticket: https://jira.uitdatabank.be/browse/III-6000

III-6000 - Show generic error when multiple duplicate places

---

src/layouts/index.js

- [early return if currentPath and path are /search](https://github.com/cultuurnet/udb3-frontend/commit/8fff20ac2bac4c28491450e708501599047623bb)
- Broken link
---
Ticket: https://jira.uitdatabank.be/browse/III-6017

III-6017 - Add early return if currentPath and path are /search

---

src/hooks/useHandleWindowMessage.js
src/layouts/Sidebar.tsx

- [new type to WindowMessageTypes](https://github.com/cultuurnet/udb3-frontend/commit/3f24950b858ed9efdb108b59f292751736f1daf7)
- [announcement modal when received message from iframe](https://github.com/cultuurnet/udb3-frontend/commit/bbe06c020c5ab9bc7d9ea2ff9dafd4fa1f920569)
---
Ticket: https://jira.uitdatabank.be/browse/III-6123

III-6123 - Open announcement modal when received message from iframe (udb3-angular)

---

src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json
src/pages/dashboard/index.page.tsx

- [completeness sorting](https://github.com/cultuurnet/udb3-frontend/commit/afce2beda5204549885916ce069ebe61d75035e1)
---
Ticket: https://jira.uitdatabank.be/browse/III-6042

III-6042 - Add completeness sorting

---

src/layouts/index.js

- [early return always do a full page refresh](https://github.com/cultuurnet/udb3-frontend/commit/6ee69ffe9b78ab1aeea77a9058ebcb85f67088e3)
https://github.com/cultuurnet/udb3-frontend/assets/9402377/5025b3ae-59c5-4508-a470-f3821a53798c
---
Ticket: https://jira.uitdatabank.be/browse/III-6016

III-6016 - Search page  (always do a full page refresh)

---

src/pages/OrganizerAddModal.tsx
src/pages/PlaceAddModal.tsx
src/pages/steps/NameStep.tsx
src/ui/FormElement.tsx
src/ui/Input.tsx

- Added character counter/limit to name fields
---
Ticket: https://jira.publiq.be/browse/III-6114

Added character counter/limit to name fields

---

src/ui/FormElement.tsx

- Changed appearance of character counter
---
Ticket: https://jira.publiq.be/browse/III-6114

Changed appearance of character counter

---

src/pages/steps/NameStep.tsx
src/ui/FormElement.tsx

- Always put info text under input, and label in its place
---
Ticket: https://jira.publiq.be/browse/III-6114

Always put info text under input, and label in its place

---

src/ui/FormElement.stories.mdx
src/ui/FormElement.tsx

- Fixed non TOP label position not being respected anymore
---
Ticket: https://jira.publiq.be/browse/III-6152

Fixed non TOP label position not being respected anymore

---

src/hooks/api/newsletter.ts

- Changed mailing list logic to new endpoint
---
Ticket: https://jira.publiq.be/browse/III-6148
Requires https://jira.publiq.be/browse/III-6068 to be deployed first

Changed mailing list logic to new endpoint

---

src/hooks/api/newsletter.ts

- Update mailing list subscription endpoint
---
Ticket: https://jira.publiq.be/browse/III-6163

Update mailing list subscription endpoint

---

playwright.config.ts
src/pages/_app.page.js
src/pages/steps/StepsForm.tsx
src/test/e2e/create-movie.spec.ts
src/test/e2e/events/create-uitpas-event.spec.ts

- "Fixed" calendar not listening for changes after initial save
---
I couldn't find what the bug was, every time I tracked a location which, when modified, made it work, it would break down as I start to fix it or un-isolate parts. I'm not saying this is a hard bug, I'm saying I'm missing it, perhaps it's tunnel vision. 😅 
ANYWAYS I did know that it was due to the page transition to the `/edit` page messing with the state machine, so of course any good old refresh fixed it. So uh yeah now it refreshes to avoid the bug. It still keeps scroll position and all so it's just an extra flash of white but I'm open to leads for a more future-proof fix :/ 
Ticket: https://jira.publiq.be/browse/III-6110

"Fixed" calendar not listening for changes after initial save

---

src/pages/Footer.tsx

- Fixed footer link to documentation
---
Ticket: https://jira.publiq.be/browse/III-6057

Fixed footer link to documentation

---

src/pages/_app.page.js

- Fixed unsafe runtime config access in app layout

Fixed unsafe runtime config access in app layout

---

src/pages/steps/LocationStep.tsx

- Fixed Recent Locations columns exceeding their max allocated width
---
Ticket: https://jira.publiq.be/browse/III-6203

Fixed Recent Locations columns exceeding their max allocated width

---

README.md

- Updated path of appconfig
- Related pull request https://github.com/cultuurnet/appconfig/pull/777
---
Ticket: https://jira.uitdatabank.be/browse/III-4932

III-4932 Update path of appconfig

---

.github/workflows/ci.yml
.github/workflows/e2e.yml
package.json
src/pages/[...params].page.js
src/pages/steps/CalendarStep/CalendarStep.tsx
src/test/e2e/events/create-calendar-single.spec.ts
src/test/e2e/setup/auth.setup.ts
src/utils/formatDateToISO.ts
yarn.lock

- Ensure the timezone offset of the date being checked is used instead of local
---
Ticket: https://jira.publiq.be/browse/III-6277

Ensure the timezone offset of the date being checked is used instead of local

---

src/pages/steps/AdditionalInformationStep/PriceInformation.tsx

- Handle error from backend if price name not unique
---
Ticket: https://jira.uitdatabank.be/browse/III-6239

III-6239 - Handle error from backend if price name not unique

---

src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json
src/pages/steps/AdditionalInformationStep/ContactInfoStep.tsx
src/utils/isValidInfo.ts

- Make http(s) required in contact point
---
Ticket: https://jira.uitdatabank.be/browse/III-6267

III-6267 - Make http(s) required in contact point

---

src/pages/organizers/[organizerId]/ownerships/index.page.tsx

- [Add getServerSideProps](https://github.com/cultuurnet/udb3-frontend/commit/72f982e4696346b60136bd57340d177f7fc05666)
- Fix prerender issue

Fix prerender issue

---

src/pages/[...params].page.js

Fix ff ownership

---

src/hooks/api/ownerships.ts
src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json
src/pages/organizers/[organizerId]/ownerships/OwnershipsTable.tsx
src/pages/organizers/[organizerId]/ownerships/index.page.tsx
src/ui/Alert.tsx
src/ui/Button.tsx
src/ui/Icon.tsx
src/ui/Page.tsx
src/ui/theme.ts

- Ownerships page
- Ownerships table
- Icon times circle
- Icon arrow left
- Alert full width
---
Ticket: https://jira.uitdatabank.be/browse/III-6357

III-6357-Ownerships page

---

next.config.js
src/pages/dashboard/DashboardRow.tsx

Fix dashboard images

---

src/pages/dashboard/DashboardRow.tsx

- Dashboard styling
---
Ticket: https://jira.uitdatabank.be/browse/III-6376

III-6376 - Improve dashboard styling

---

src/layouts/index.js
src/middleware.api.ts
src/pages/[...params].page.js

- Fix looping bugs on iframe url change
---
Ticket: https://jira.publiq.be/browse/III-6325

Fix looping iframe url change

---

.github/CODEOWNERS

Add vhande to codeowners

---

src/redirects.tsx

- Add redirect for manage organisations
---
Ticket: https://jira.uitdatabank.be/browse/III-6327

III-6327 - Add redirect for manage organisations

---

src/hooks/useHandleWindowMessage.js
src/hooks/useLegacyPath.tsx
src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json
src/middleware.api.ts
src/pages/[...params].page.js
src/pages/search/index.page.tsx
src/ui/Tabs.tsx

- Search page
- useLegacyPath
---
Ticket: https://jira.uitdatabank.be/browse/III-6325

III-6325 - Add tabs to search page

---

src/pages/search/index.page.tsx
src/redirects.tsx

- Redirects
---
Ticket: https://jira.uitdatabank.be/browse/III-6327

III-6327- Manage redirects

---

src/pages/organizers/[organizerId]/ownerships/index.page.tsx

- Ownership page organizer name
---

Fix ownership organizer name

---

README.md

- Updated the path `env`-file in appconfig, for running the frontend in combination with `docker`
- Added note about the need the rename `env` to `.env`
---

update README after changes in appconfig

---

src/pages/organizers/[organizerId]/ownerships/index.page.tsx
src/pages/organizers/[organizerId]/preview/index.page.tsx

- Added icons to various ownerships buttons
---
Ticket: https://jira.publiq.be/browse/III-6422

Added icons to various ownerships buttons

---

src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json

- Tweak copy of Back button in organizer preview page
---
Ticket: https://jira.publiq.be/browse/III-6423

Tweak copy of Back button in organizer preview page

---

src/i18n/de.json
src/i18n/fr.json
src/pages/dashboard/index.page.tsx
src/pages/organizers/[organizerId]/ownerships/index.page.tsx
src/pages/organizers/[organizerId]/preview/RequestOwnershipModal.tsx
src/pages/organizers/[organizerId]/preview/index.page.tsx
src/pages/organizers/create/steps/UrlStep.tsx

- Added ability to request suggested ownership
---
Ticket: https://jira.publiq.be/browse/III-6362

Added ability to request suggested ownership

---

src/pages/steps/hooks/useRecentLocations.ts

- Fixed unusable locations showing in Recent Locations
---
Ticket: https://jira.publiq.be/browse/III-6333

Fixed unusable locations showing in Recent Locations

---

.github/workflows/e2e.yml
src/pages/organizers/[organizerId]/ownerships/OwnershipsTable.tsx
src/pages/organizers/[organizerId]/ownerships/index.page.tsx

- Fixed ownerships table not showing creator when no results
---
Ticket: https://jira.publiq.be/browse/III-6508
@BenGabriels1 That makes it look like that, would it be better?

Fixed ownerships table not showing creator when no results

---

src/i18n/nl.json

- Fixed typo in organizer preview page[Fixed ...]
---
Ticket: https://jira.publiq.be/browse/III-6473

Fixed typo in organizer preview page

---

src/pages/steps/AdditionalInformationStep/ContactInfoStep.tsx

- Contact info
---
Ticket: https://jira.uitdatabank.be/browse/III-6064

III-6064-Fix contact info

---

package.json
yarn.lock

This PR is a piece of the multiple changes done in https://github.com/cultuurnet/udb3-frontend/pull/974
- Update typescript
---

III-6516 - Update typescript

---

src/hooks/api/labels.ts
src/hooks/api/offers.ts
src/hooks/api/organizers.ts
src/hooks/api/ownerships.ts
src/hooks/api/places.ts
src/hooks/api/productions.ts
src/hooks/api/user.ts
src/types/PaginatedData.ts

- [Add PaginatedData type](https://github.com/cultuurnet/udb3-frontend/commit/470e40620b2f6ef7bbab9660b072f1549fe0112a)
- [Add return types to fetch functions](https://github.com/cultuurnet/udb3-frontend/commit/57d082def806107be65ac002d72e5cc80c75fd65)
---

III-6516 - Add return types to fetches

---

Jenkinsfile

- Change label nodejs jenkins
---
Ticket: https://jira.publiq.be/browse/III-6355

III-6355 - Change label nodejs jenkins

---

src/middleware.api.ts

Use baseUrl from env

---

src/hooks/api/authenticated-query.ts
src/hooks/api/events.ts
src/hooks/api/offers.ts
src/hooks/api/organizers.ts
src/hooks/api/ownerships.ts
src/hooks/api/places.ts
src/hooks/api/productions.ts
src/hooks/api/user.ts
src/pages/dashboard/index.page.tsx
src/pages/events/[eventId]/availability.page.js
src/pages/events/[eventId]/duplicate/index.page.tsx
src/pages/events/[eventId]/edit/index.page.tsx
src/pages/manage/movies/[eventId]/edit.page.tsx
src/pages/manage/productions/index.page.js
src/pages/organizers/[organizerId]/edit/index.page.tsx
src/pages/organizers/[organizerId]/ownerships/index.page.tsx
src/pages/organizers/[organizerId]/preview/index.page.tsx
src/pages/places/[placeId]/availability.page.js
src/pages/steps/hooks/useRecentLocations.ts
src/test/e2e/setup/auth.setup.ts
src/utils/fetchFromApi.ts
src/utils/getApplicationServerSideProps.js

- queryOptions and prefetch functions for different queries
- Make ServerSideQueryOptions properties required
- TODOs for prefetches
- optional chaining
- to much was being passed to queryParams for certain queryFns
---

III-6516 - Add prefetches on serverside

---

src/hooks/api/events.ts
src/hooks/api/organizers.ts
src/hooks/api/productions.ts
src/test/e2e/create-organizer.spec.ts

- Make usage of params explicit
---

III-6516 - Fix passing wrong params to api calls

---

src/hooks/api/events.ts
src/hooks/api/organizers.ts
src/hooks/api/places.ts

- Pass sorting and calendarSummary embed to dashboard queries
- Fix dashboard sorting

Fix dashboard sorting

---

src/constants/EventTypes.ts
src/pages/steps/EventTypeAndThemeStep.tsx

- Cultuurkuur types
---
Ticket: https://jira.uitdatabank.be/browse/III-6558

III-6558-Add Cultuurkuur types

---

src/pages/organizers/[organizerId]/preview/index.page.tsx

- Fixed Pending and Requested ownership alerts showing at the same time
---
Ticket: https://jira.publiq.be/browse/III-6575

Fixed Pending and Requested ownership alerts showing at the same time

---

src/constants/OfferType.ts
src/pages/dashboard/DashboardPictureUploadModal.tsx
src/pages/dashboard/DashboardRow.tsx
src/pages/steps/AdditionalInformationStep/AdditionalInformationStep.tsx
src/pages/steps/LocationStep.tsx

III-6516 - Fix Scope type issues

---

lib/tasks/uitdatabank-frontend.service
src/constants/AudienceType.ts
src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json
src/pages/create/OfferForm.tsx
src/pages/manage/movies/MovieForm.tsx
src/pages/steps/AudienceStep.tsx
src/pages/steps/EventTypeAndThemeStep.tsx
src/pages/steps/LocationStep.tsx
src/pages/steps/ScopeStep.tsx
src/pages/steps/Steps.tsx
src/pages/steps/StepsForm.tsx
src/types/Event.ts
src/types/Offer.ts
src/ui/RadioButton.tsx

- Cultuurkuur toggle
- Audience type
---
Ticket: https://jira.uitdatabank.be/browse/III-6557

III-6557-Add Cultuurkuur toggle

---

src/layouts/Sidebar.tsx

- Deduplicate constraints before passing to query

Fix failing e2e tests due to long url

---

src/pages/steps/AdditionalInformationStep/PriceInformation.tsx

- [Fixed ...]
- gratis button
---

Fix gratis button

---

src/hooks/api/ownerships.ts
src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json
src/pages/organizers/[organizerId]/ownerships/OwnershipsTable.tsx

- [Add ModificationInfo](https://github.com/cultuurnet/udb3-frontend/pull/1011/commits/c08420c3c4ecbc292d5d07c12dfdb4dada71d159)
- [Add status to ownerships table](https://github.com/cultuurnet/udb3-frontend/pull/1011/commits/4460e208ce926203d39c652bc492cc25ae7e402b)
- [Add translations](https://github.com/cultuurnet/udb3-frontend/pull/1011/commits/df82e6f51c4c0d1a8ed4b8fd9482a5e81dcbb31c)
- [Only show status on reject and approve](https://github.com/cultuurnet/udb3-frontend/pull/1011/commits/203a4c1863b4d53a0e27401cb150356fcece4f49)
---
Ticket: https://jira.uitdatabank.be/browse/III-6583

III-6583 - Small visual improvements 2

---

src/i18n/nl.json
src/pages/steps/AdditionalInformationStep/PriceInformation.tsx
src/types/Offer.ts

- select group price
- no price alert
Ticket: https://jira.uitdatabank.be/browse/III-6563

III-6563-Add group price

---

src/i18n/nl.json
src/pages/steps/EventTypeAndThemeStep.tsx
src/pages/steps/StepsForm.tsx

- Validate Cultuurkuur event type on duplicate events conversion
---
Ticket: https://jira.uitdatabank.be/browse/III-6589

III-6589-Validate Cultuurkuur Event Type

---

src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json
src/pages/organizers/[organizerId]/ownerships/OwnershipsTable.tsx
src/pages/steps/EventTypeAndThemeStep.tsx
src/ui/RadioButtonWithLabel.tsx

- date display
- <br/ > tags
- eslint warnings 
---
Ticket: https://jira.uitdatabank.be/browse/III-6604

III-6604-Small improvements

---

src/i18n/nl.json
src/pages/steps/AdditionalInformationStep/PriceInformation.tsx

- Clear price info and show alert when duplicating to Cultuurkuur
---
Ticket: https://jira.uitdatabank.be/browse/6605

UIT-6605-Remind user to review price when converting to Cultuurkuur event

---

src/pages/organizers/[organizerId]/ownerships/index.page.tsx

- Fixed Ownership Organizer modal not being cleared on success
---
Ticket: https://jira.publiq.be/browse/III-6600

Fixed Ownership Organizer modal not being cleared on success

---

src/pages/steps/LocationStep.tsx

- cultuurkuur_op_verplaatsing label to in consultation locations
---
Ticket: https://jira.uitdatabank.be/browse/III-6637

III-6637-Add cultuurkuur_op_verplaatsing to in consultation locations

---

src/pages/organizers/create/steps/CultuurkuurStep.tsx
src/pages/organizers/create/steps/UrlStep.tsx

- Disable CK organizer toggle
---
Ticket: https://jira.uitdatabank.be/browse/III-6648

III-6648-Disable CK organizer toggle

---

src/hooks/api/cultuurkuur.ts

Fix label filtering

---

src/i18n/nl.json
src/pages/steps/NameAndAgeRangeStep.tsx

- Education levels info text
- Styling
---
Ticket: https://jira.uitdatabank.be/browse/III-6652

III-6652-Edit info text

---

src/i18n/nl.json
src/pages/steps/AdditionalInformationStep/CultuurKuurStep.tsx
src/pages/steps/CultuurkuurLabelsPicker.tsx
src/pages/steps/CultuurkuurSelectionOverview.tsx

- Selection overview
---
Ticket: https://jira.uitdatabank.be/browse/III-6650

III-6650-Selection overview

---

src/pages/organizers/[organizerId]/preview/OrganizerLabels.tsx
src/pages/steps/AdditionalInformationStep/LabelsStep.tsx

- Check permissions instead of roles to show cultuurkuur labels
---

Use permissions instead of roles

---

.github/CODEOWNERS

- Removed Emma from CODEOWNERS
- Removed Simon from CODEOWNERS
- Removed Paul from CODEOWNERS

Remove Emma & Simon & Paul from CODEOWNERS

---

.github/CODEOWNERS

Add bert to codeowners

---

src/i18n/nl.json
src/pages/AlertDuplicatePlace.tsx
src/pages/PlaceAddModal.tsx
src/pages/steps/LocationStep.tsx
src/pages/steps/NameAndAgeRangeStep.tsx
src/pages/steps/StepsForm.tsx
src/pages/steps/hooks/useEditField.ts
src/utils/checkDuplicatePlace.ts
src/utils/fetchFromApi.ts

- CustomValidatonError
- CheckDuplicatePlace
- AlertDuplicatePlace
---
Ticket: https://jira.uitdatabank.be/browse/III-6718

III-6718-Handle new duplicate place error when updating an existing place

---

src/pages/manage/productions/Events.js
src/pages/manage/productions/index.page.js

- [Also trigger name change on enter](https://github.com/cultuurnet/udb3-frontend/commit/e4ec280cf7eb57c9aa7023d23c94e273dc7a1ef9)
- [query key for optimistic update](https://github.com/cultuurnet/udb3-frontend/commit/940c3a359c290d6a8ff4a1fde00aacc9de1097db)
---
Ticket: https://jira.uitdatabank.be/browse/III-6781

III-6781 - Fix error when trying to change production name

---

src/test/e2e/cultuurkuur/create-cultuurkuur-event.spec.ts
src/test/e2e/cultuurkuur/create-cultuurkuur-organizer.spec.ts

- E2E test for cultuurkuur event creation
- E2E test for cultuurkuur organizer creation
---
Ticket: https://jira.publiq.be/browse/III-6781

III-6568 - Set up e2e test for cultuurkuur event/organizer creation

---

src/utils/uitpas.ts

- Uitpas location check: [Also check hiddenLabels](https://github.com/cultuurnet/udb3-frontend/commit/8f7795732d1b21dad56a6feb4486bdb6a30b34e2)
---
Ticket: https://jira.uitdatabank.be/browse/III-6685

III-6685 - Also check hiddenLabels

---

src/hooks/api/places.ts

[Fixed]
- editing a place address
---
Ticket: https://jira.uitdatabank.be/browse/III-6788

III-6788-Fix editing a place address

---

.github/workflows/chromatic.yml

- [buildScriptName](https://github.com/cultuurnet/udb3-frontend/commit/d21359e1dafa10f5e9fdbd8ae027f10dbc2f46fd)

Add buildScriptName for chromatic ci job

---

src/pages/steps/AdditionalInformationStep/PriceInformation.tsx

- UiTPAS validation error stricter
---
Ticket: https://jira.uitdatabank.be/browse/III-6270

III-6270-Make UiTPAS validation error stricter

---

src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json
src/pages/dashboard/index.page.tsx

- copy and alignment in 'Mijn organisaties'
---
Ticket: https://jira.uitdatabank.be/browse/III-6817

III-6817-Change copy and alignment in 'Mijn organisaties'
