components/legacy-app-page.vue
components/sidebar.vue

- Fixed an issue where clicking e.g. on the `Dashboard` link, then clicking a link inside the resulting iframe, and then clicking the `Dashboard` link again would not result in the dashboard being shown. By pushing the location change to the Vue router, Vue treats it as a navigation change so when clicking the `Dashboard` link later again this will also be treated as a navigation change. Otherwise Vue thinks the user is still on the `Dashboard` page even though another page is shown inside the iframe. This will cause a double refresh of content in the iframe though. To fix that there's an additional PR in the udb3-angular-app repository: https://github.com/cultuurnet/udb3-angular-app/pull/149
---
Ticket: https://jira.uitdatabank.be/browse/III-3382

III-3382 Push iframe location changes to the Vue router

---

pages/index.vue

- Fixed the AngularJS "main" screen being visible for a split second while AngularJS did the redirect from `/` to `/dashboard` inside the iframe, by making the Vue app do the redirect instead before rendering the iframe

Make the Vue app redirect from / to /dashboard

---

api/api.js
api/events.js
api/user.js
components/button-logout.vue
components/giftbox.vue
components/legacy-app-page.vue
middleware/auth.js
nuxt.config.js
package.json
pages/login.vue
plugins/api.js
services/auth.js
yarn.lock

- Removed usages of `process.env.` outside of the `publicRuntimeConfig` in `nuxt.config.js`. Otherwise these env variables would get interpolated (i.e. hardcoded) during build, preventing us from running the same build on different environments with different `.env` files. See https://nuxtjs.org/blog/moving-from-nuxtjs-dotenv-to-runtime-config/
---
Ticket: https://jira.uitdatabank.be/browse/III-3347

III-3347 Make nuxt env variables public runtime config

---

components/giftbox.vue
components/sidebar.vue
i18n/fr.json
i18n/nl.json
layouts/default.vue

- a count of unseen features
- the giftbox-button to be a link within the sidebar
- the giftbox-button
---
Ticket: https://jira.uitdatabank.be/browse/III-3406
After changes:

Feature/iii 3406 Styling of the gift box depends on the items a user has read

---

assets/styles/_custom-bootstrap.scss
components/giftbox.vue
i18n/fr.json
i18n/nl.json

- more semantic html elements
- styling of giftbox to resemble other modals like in advanced search
- title that wasn't ellipsing when too long
---
Ticket: https://jira.uitdatabank.be/browse/III-3416
Screenshot:

Feature/iii 3416 Optimize styling giftbox

---

api/productions.js

- The suggestions endpoint was changed to return `204` (no content) in case of no suggestions, so we need to change the check in the frontend
---
Ticket: https://jira.uitdatabank.be/browse/III-3464
Related PRs:
- https://github.com/cultuurnet/udb3-silex/pull/488
- https://github.com/cultuurnet/udb3-swagger/pull/61

Check for 204 in case of no suggestions instead of 404

---

components/productions/create/event.vue
pages/manage/productions/create.vue

- feature/III-3491 - add locationName and locationCity information to event cards on create page
---
Ticket: https://jira.uitdatabank.be/browse/III-3491

feature/III-3491 - add locationName and locationCity information to event cards on create page

---

components/productions/index/events.vue
pages/manage/productions/create.vue
publiq-ui/pub-alert.stories.mdx
publiq-ui/pub-alert.vue

'alert' isn't a known variant, thus was a typo
- change variant from 'alert' to 'warning'
- pub-alert styling
---
Screenshot:
Ticket: https://jira.uitdatabank.be/browse/III-3459

III-3459 - change variant from 'alert' to 'warning'

---

publiq-ui/pub-link.stories.mdx
publiq-ui/pub-link.vue

- Fixed `pub-link`'s color. Reboot.css was overwriting the color of all `a` tags. By adding a class and making our selector more specific, our selector has precedence.

Fix pub-link's color

---

components/giftbox.vue

- styling a-tag for v-html section
---
Screenshot after changes:
Ticket: https://jira.uitdatabank.be/browse/III-3518

set styling a-tag for v-html section

---

publiq-ui/pub-typeahead.vue

- prefilled input similarity ui
The prop passed when using v-model has to be called `value` for it to work.
---
Ticket: https://jira.uitdatabank.be/browse/III-3522
Screenshot:

III-3522 - fix prefilled input similarity ui  

---

components/login.vue
i18n/fr.json
middleware/auth.js
pages/login/fr.vue
pages/login/index.vue
pages/login/nl.vue

- new route `/login/nl`
- new route `/login/fr`
- place of `login.vue` from `pages` to `components`
---
Ticket: https://jira.uitdatabank.be/browse/III-3151

Feature/iii 3151 - use different urls for the login page according to the language

---

src/components/publiq-ui/Button.js
src/components/publiq-ui/Link.js

- Fixed a layout issue by using `forwardAs` instead of `as` since we apply some custom CSS

Use forwardAs instead of as

---

src/components/SideBar.js

- This should prevent all menu items from showing when the permissions aren't loaded yet

Return an empty array when loading

---

src/components/publiq-ui/Page.js

- The actual types are minified on the production build, so the page was gone. This fixes it

Compare against actual components

---

src/components/manage/productions/index/DeleteModal.js
src/i18n/fr.json
src/i18n/nl.json

- Modal that is shown when removing an event from a production now has a proper title
---
Ticket: https://jira.uitdatabank.be/browse/III-3688

III-3688 - Empty modal header in productions frontend

---

src/components/SideBar.js

- regain focus on mouse over on sidebar (need to do a setTimeout trick to make it work)
---
Ticket: https://jira.uitdatabank.be/browse/III-3727

Regain focus on MouseOver

---

src/utils/getApplicationServerSideProps.js

- error would trigger in Firefox when there was no cookie

Default empty cookie when there is none found

---

package.json
yarn.lock

- [deprecated react-query-devtools](https://github.com/tannerlinsley/react-query-devtools#readme)
---

Remove deprecated react-query-devtools

---

src/hooks/api/authenticated-query.js

- Use lodash flatten() instead of Array.prototype.flat() for node 10 compatibility. (The servers and Vagrant box use node 10 right now, and while we should look into updating that it might take some work to get udb3-websockets etc compatible with newer versions, so we should make sure udb3-frontend can be deployed in the meantime.)
---
Ticket: https://jira.uitdatabank.be/browse/III-3825

III-3825 Use lodash flatten() instead of Array.prototype.flat()

---

src/ui/Typeahead.js
src/ui/Typeahead.stories.mdx
src/ui/TypeaheadWithLabel.js
src/ui/TypeaheadWithLabel.stories.mdx
src/ui/theme.js

- Added the typeahead highlight to bold
- Changed the typeahead selection color
- Fixed typeahead with label by removing autogenerated id
---
Ticket: https://jira.uitdatabank.be/browse/III-3794

III-3794 Add typeahead selection color

---

src/components/layouts/joblogger/JobLogger.js

- Fixed failed jobs showing up as succeeded. The backend still sends a "finished" message for every job, even if it failed. We don't want to treat those failed jobs as succeeded though. (Noticed this while testing some exceptions/errors in context of III-3816)
---
Ticket: https://jira.uitdatabank.be/browse/III-3816

III-3816 Prevent jobs from transitioning from failed to finished

---

src/components/StatusPageMultiple.js
src/components/StatusPageSingle.js
src/components/layouts/Sidebar.js
src/components/layouts/index.js
src/components/pages/manage/productions/create/Event.js
src/components/pages/manage/productions/create/index.js
src/components/pages/manage/productions/index/Events.js
src/components/pages/manage/productions/index/index.js

- Use the same naming for queries and mutations throughout the application
e.g. 
`const getProductionsQuery = useGetProductions()`
`const addEventsByIdsMutation = useAddEventsByIds()`

Improvement - Refactor naming of react-query mutations and queries

---

src/components/pages/manage/productions/create/index.js
src/ui/Typeahead.js
src/ui/Typeahead.stories.mdx

- Add min length to typeahead to only trigger search when this min length is reached
---
Ticket: https://jira.uitdatabank.be/browse/III-3893

III-3893 Add min length to typeahead

---

src/components/pages/manage/productions/create/index.js
src/i18n/fr.json
src/i18n/nl.json
src/ui/Typeahead.js
src/ui/Typeahead.stories.mdx
src/ui/TypeaheadWithLabel.js

- Add minLength on TypeaheadWithLabel
- Fixed placeholder for production search
- Give minLength a default value of 3
---
Ticket: https://jira.uitdatabank.be/browse/III-3893

III-3893 Add minLength on TypeaheadWithLabel

---

src/components/layouts/Sidebar.js
src/ui/Button.js
src/ui/List.js

- Removed `tabindex` from sidebar so it doesn't get focus when hovering or tabbing
- Removed `tabindex` from list items so you don't need to tab twice (once for the list item, and again for the link/button inside)
- Fixed invisble focus outlines on links and buttons when navigating by keyboard by resetting the outlines of buttons to `auto`, and only hiding it when not using the keyboard (see https://css-tricks.com/keyboard-only-focus-styles/)
---
Ticket: https://jira.uitdatabank.be/browse/III-3759
To test this I'd suggest to tab around a page (`/manage/productions` is a good one) in Chrome and look if the order makes sense, nothing gets skipped, and the focused element is always clearly visible.
If you use Firefox, links are not tab-able by default on macOS. So you will only be tabbing …

III-3759 Fix focus outlines

---

next.config.js

- Made redirects only permanent when not in the `development` environment, to prevent issues with other projects running on `localhost`

Don't make redirects permanent on localhost

---

src/ui/Link.js
src/ui/Link.stories.mdx

This PR illustrates the issue with `display: flex` on links.
You can view the Story that illustrates it on https://5f69c0eb52e6b60022561d99-jyexhyrsvo.chromatic.com/?path=/story/components-link--internal
On the Story for the unstyled variant with text, there is a similar/related issue: https://5f69c0eb52e6b60022561d99-jyexhyrsvo.chromatic.com/?path=/story/components-link--unstyled-external
The unstyled variant has `width: min-content`, which was probably meant to undo the 100% width set by `display: flex`, but makes the text inside the link wrap to multiple lines while it could fit on a single line.

Bug with display: flex on links

---

next.config.js
package.json
src/components/layouts/index.js
src/components/pages/[...params].js
src/hooks/useFeatureFlag.js
src/redirects.js
yarn.lock

- Added "client-side" redirects (you can test this by going to the detail page of an event and clicking the "Status wijzigen" button -> This should redirect from `/event/:eventId/status` to `/events/:eventId/status`)
- Added possibility to put redirects handled by `[...params].js` behind feature flags (so only works for paths that don't exist in React, which should be fine for the porting of AngularJS pages to React and making the AngularJS pages redirect when the React page is finished)
- Changed 404 logic to only listen for `URL_UNKNOWN` messages in the `Fallback` component, because if it was registered sooner in the app itself the 404 logic would conflict with the redirect logic and sometimes a page that should redirect would show 404 instead because the iframe would be rendered and …

Fix client side redirects

---

src/ui/Text.js
src/ui/Text.stories.mdx
src/ui/theme.js

- Added `MUTED` variant for `Text` component
---
Ticket: https://jira.uitdatabank.be/browse/III-3997
Will be needed on the dashboard for past events, for example on the current one in AngularJS:

Add muted text variant

---

src/components/pages/login/[language].js
src/components/pages/manage/productions/index/Events.js
src/components/pages/manage/productions/index/Productions.js
src/ui/Alert.js
src/ui/Badge.js
src/ui/Button.js
src/ui/Card.js
src/ui/Checkbox.js
src/ui/CheckboxWithLabel.js
src/ui/DetailTable.js
src/ui/Icon.js
src/ui/Image.js
src/ui/Input.js
src/ui/InputWithLabel.js
src/ui/Label.js
src/ui/Link.js
src/ui/List.js
src/ui/Logo.js
src/ui/Pagination.js
src/ui/Panel.js
src/ui/RadioButton.js
src/ui/RadioButtonGroup.js
src/ui/RadioButtonWithLabel.js
src/ui/Small.js
src/ui/Spinner.js
src/ui/Text.js
src/ui/TextArea.js
src/ui/TextAreaWithLabel.js
src/ui/Typeahead.js
src/ui/TypeaheadWithLabel.js

- boxPropTypes, stackPropTypes and inlinePropTypes aren't objects with proptypes anymore but an array of strings
```
Warning: Failed prop type: Checkbox: prop type `35` is invalid; it must be a function, usually from the `prop-types` package, but received `string`.This often happens because of typos such as `PropTypes.function` instead of `PropTypes.func`.
```

Remove incorrect boxPropTypes usage

---

src/components/pages/dashboard.tsx
src/utils/fetchFromApi.ts

- Use Promise.all instead of Promise.allSettled
We're currently using node 10 in the vragant box, Promise.allSettled is only supported in Node 12.19 and upwards
---

Use Promise.all

---

src/components/Footer.tsx
src/components/pages/dashboard/NewsletterSingupForm.tsx
src/components/pages/dashboard/index.tsx
src/components/pages/login/Footer.tsx
src/components/pages/login/[language].tsx

- Extracted Footer from login page and reused it on the dashboard page
- added a boolean to disable the language switcher on the dashboard page

Add footer to dashboard page

---

src/components/Footer.tsx
src/components/pages/dashboard/index.tsx

- default changeLanguage handler (different behaviour on the login page)
- always show it by default in the footer

Enable language switcher in footer by default

---

.storybook/preview-head.html
.storybook/preview.js
src/components/pages/_app.js
src/components/pages/_document.js
src/pages/_app.js
src/styles/global.scss

- Server Side render not including all styles (bootstrap)
We're now also making use of https://nextjs.org/docs/basic-features/font-optimization
---
Ticket: https://jira.uitdatabank.be/browse/III-3789
Screenshot BEFORE:
Screenshot AFTER:

III-3789 - fix bootstrap styles serverside

---

src/components/pages/dashboard/index.tsx
src/hooks/api/authenticated-query.ts
src/hooks/api/events.ts
src/hooks/api/places.ts
src/utils/createEmbededCalendarSummaries.ts
src/utils/createSortingArgument.ts

- option for calendarSummaryFormats in api calls
- conditional to show lg-text when calendarType is single
- fetch md-text and lg-text for getByCreator
---
Ticket: https://jira.uitdatabank.be/browse/III-4090

III-4090 - calendar summary

---

src/components/layouts/joblogger/Job.tsx

- Only show download button when export job finished
Note: I was not able to reproduce this but added an extra check to verify if the job finished before showing the download button
---
Ticket: https://jira.uitdatabank.be/browse/III-4181

III-4181 Only show download button when export job finished

---

src/components/layouts/index.js

-  Prevent /search to be refreshed when url params are added (temporary fix until `/search` is ported to react
---
Ticket: https://jira.uitdatabank.be/browse/III-4409

III-4409 - Prevent /search to be refreshed when url params are added

---

src/i18n/nl.json
src/pages/manage/movies/MoviePage.tsx

- ready with edit button on footer of film edit form
---
Ticket: https://jira.uitdatabank.be/browse/III-4615

III-4615 - Add ready with edit button on footer of film edit form

---

src/pages/manage/movies/MovieForm.tsx
src/pages/manage/movies/useAddEvent.ts
src/pages/manage/movies/useEditField.ts
src/pages/manage/movies/useGetEvent.ts
src/pages/manage/movies/usePublishEvent.ts
src/pages/manage/movies/useToast.tsx
src/pages/steps/EventTypeAndThemeStep.tsx
src/pages/steps/PlaceStep.tsx
src/pages/steps/ProductionStep.tsx
src/pages/steps/TimeTableStep.tsx

- Moved the edit hooks to their own steps
- Moved the edit / publish / save / toast hooks to their own files.
- the editMap functionality
The next step is to move the "edit" logic to the steps themselves.

Move hooks to own files / steps

---

yarn.lock

- [swc/plugin-styled-components since it isn't used](https://github.com/cultuurnet/udb3-frontend/commit/a81f05e6598ceb67eca8a195cb9a82a07df6b16e)
I did:
`nvm use`
`rm -rf node_modules`
`yarn install`

Remove swc/plugin-styled-components since it isn't used

---

src/pages/OrganizerAddModal.tsx
src/pages/dashboard/index.page.tsx
src/pages/steps/PriceInformation.tsx
src/ui/Alert.stories.mdx
src/ui/Alert.tsx
src/ui/Icon.tsx

- New `primary`  bootstrap AlertVariant 
- Icons on alerts
- use `primary` AlertVariant instead of `info`
---
Ticket: https://jira.uitdatabank.be/browse/III-5021

III-5021 - Alert improvements

---

src/pages/steps/OrganizerPicker.tsx
src/styles/GlobalStyle.js
src/ui/Badge.tsx
src/ui/theme.ts

- Make organizer buttons less large
- Use global border radius
- Badge secondary: use same grey as for step numbers
---
Ticket: https://jira.uitdatabank.be/browse/III-5032

III-5032 - Organizer picker refinements

---

src/pages/steps/PriceInformation.tsx
src/ui/Alert.tsx
src/ui/Box.tsx
src/ui/Inline.tsx

- Don't make alerts full-width
**Screenshots**
---
Ticket: https://jira.uitdatabank.be/browse/III-4923

III-4923 - Don't make alerts full-width

---

src/layouts/joblogger/Job.tsx
src/layouts/joblogger/JobLoggerStateIndicator.tsx
src/pages/steps/AdditionalInformationStep.tsx
src/pages/steps/EventTypeAndThemeStep.tsx
src/pages/steps/LocationStep.tsx
src/pages/steps/PlaceStep.tsx
src/pages/steps/ProductionStep.tsx
src/ui/Icon.tsx
src/ui/theme.ts

- hex value of color green3
- use global value for successIcon instead of too specific theming
- increase default size of icons `15px` -> `18px`
8727-a874-4541-82a0-703a197e599f.png">
---
Ticket: https://jira.uitdatabank.be/browse/III-5022

III-5022 - Success icon improvements

---

src/hooks/api/terms.ts

- Filter out unused eventtypes from terms
**Before:**
**After:**
---
Ticket: https://jira.uitdatabank.be/browse/III-5067

III-5067 - Filter out unused eventtypes from terms

---

src/pages/steps/LocationStep.tsx
src/ui/FormElement.tsx

- `labelIsBold` prop in `FormElement`
- Don't make the "online" label bold
- Make toggle bigger in LocationStep
https://codepen.io/nisharg/pen/mdJmywW
@simon-debruijn  maybe we should a seperate ui component for the toggle component in which we can integrate this custom css? I guess we always want the same size for the toggle...
Before:
After:
---
Ticket: https://jira.uitdatabank.be/browse/III-5069

III-5069 - Online toggle layout improvements

---

src/hooks/api/uitpas.ts
src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json
src/pages/steps/AdditionalInformationStep.tsx
src/pages/steps/OrganizerStep.tsx

- new `uitpas` api hook file
- show uitpas cardsystems in `OrganizerStep` component
- `AdditionalInformationStep`, select active tab based on **hash**  in url
Can be tested with following event (from acc):
- 5330a84f-7496-46a1-b60d-fa7d62ec5fb8
---
Ticket: https://jira.uitdatabank.be/browse/III-4482

III-4482 - Show CardSystems in Organizer step

---

src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json
src/pages/steps/modals/PictureUploadModal.tsx

- Image upload increase file size to 20MB
---
Ticket: https://jira.uitdatabank.be/browse/III-5095

III-5095 - Image upload increase file size to 20MB

---

src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json
src/pages/steps/CalendarStep/CalendarOpeninghoursModal.tsx

- days label to openinHoursModal
---
Ticket: https://jira.uitdatabank.be/browse/III-5157

III-5157 - Add days label to openinHoursModal

---

src/pages/steps/CalendarStep/CalendarStep.tsx

- [Correctly start and stop calendarMachine on mount and unmount of CalendarStep](https://github.com/cultuurnet/udb3-frontend/pull/505/commits/23de6225e2d1f1a49d5f94a8825de2580e259445)
- [Remove unused variables](https://github.com/cultuurnet/udb3-frontend/pull/505/commits/a4df7b5463d43e1eb3c79a612aa32699e415fbcd)
- [Fix calendar mutation to wrong scope and with undefined offerId](https://github.com/cultuurnet/udb3-frontend/pull/505/commits/a1b0e0fd424ac84acfe2693cbdf260b2c9adddda)
---
Ticket: https://jira.uitdatabank.be/browse/III-5178

III-5178 - Fix CalendarStep posting wrong data

---

src/hooks/api/places.ts
src/pages/steps/LocationStep.tsx
src/pages/steps/PlaceStep.tsx

**PlaceStep**
- Use text parameter instead of name (so that when you search for "handelsbeurs" the location with name "ha concerts" is also found)
- Disable the default filters
- Show places with workflowStatus DRAFT, READY_FOR_VALIDATION and APPROVED
- Filter out places that are duplicates from the query (isDuplicate=false)
- Filter out places that are not in Belgium (addressCountry=BE)
- Filter out places that are temporarily or permanently closed (status=Available)
- Limit the amount of results to 1000
- Sort on created (descending)
---
Ticket: https://jira.uitdatabank.be/browse/III-5134

III-5134 - PlaceStep adjust query to get relevant places

---

src/pages/steps/PlaceStep.tsx
src/ui/Box.tsx
src/ui/Typeahead.tsx

- renderMenuItemChildren as prop to `TypeAhead` and `Box`
- pass custom menuItemChildren to TypeAhead in PlaceStep
- Show Address in typeahead in PlaceStep 
---
Ticket: https://jira.uitdatabank.be/browse/III-5170

III-5170 - Show Address in typeahead in PlaceStep

---

src/ui/Button.tsx
src/ui/Input.tsx
src/ui/Typeahead.tsx
src/ui/theme.ts

- globalFormInputHeight to theme
- Make inputfields bigger
- Make buttons same height as inputfields
---
Ticket: https://jira.uitdatabank.be/browse/III-5191

III-5191 - Make button heights consistent with formInput heights

---

src/pages/steps/LocationStep.tsx
src/pages/steps/PlaceStep.tsx

- unnecessary loading state next to place TypeAhead
---
Ticket: https://jira.uitdatabank.be/browse/III-5207

III-5207 - Remove unnecessary loading state next to place TypeAhead

---

src/pages/steps/AdditionalInformationStep/OrganizerPicker.tsx

###Added:
- uitpas badge in Organizer TypeAhead
---
Ticket: https://jira.uitdatabank.be/browse/III-5198

III-5198 - Show uitpas badge in Organizer TypeAhead

---

src/hooks/api/organizers.ts
src/pages/steps/AdditionalInformationStep/OrganizerPicker.tsx

- Improve query to fetch organizers in TypeAhead
---
Ticket: https://jira.uitdatabank.be/browse/III-5210

III-5210 - Improve query to fetch organizers in TypeAhead

---

src/pages/create/OfferForm.tsx
src/pages/manage/movies/MovieForm.tsx
src/pages/steps/PlaceStep.tsx
src/pages/steps/ScopeStep.tsx
src/pages/steps/StepsForm.tsx
src/pages/steps/hooks/useFooterStatus.ts

- [Move scroll effect to StepsForm to scroll after re-render](https://github.com/cultuurnet/udb3-frontend/commit/829baa89473450f3e27499be4242541bfa438ce1)
- [Always infer offerId from url](https://github.com/cultuurnet/udb3-frontend/commit/aafba01cca9e07a4b3e8939fba57493dae7a6f28)
- [Use custom rerenderTrigger instead of url to trigger re-render](https://github.com/cultuurnet/udb3-frontend/commit/dc6751a4a108bf92ce105e114e2a26a54146f43b)
- [Fix movie form place step](https://github.com/cultuurnet/udb3-frontend/commit/0ed4cb3091663e502fcf5133e1467683c8ad5ab4)
- [Fix scope value not resetting on click create link](https://github.com/cultuurnet/udb3-frontend/commit/2558f27c85cb3367859e8d518ef222f470bb79a5)
---
Ticket: https://jira.uitdatabank.be/browse/III-5158

III-5158 - Fix scroll create form followup

---

src/pages/PictureUploadBox.tsx
src/pages/VideoUploadBox.tsx

- missing border to `VideoUploadBox`
- min-height to PictureUploadBox so boxes are aligned vertically
**Before**:
**After**:
---
Ticket: https://jira.uitdatabank.be/browse/III-5213

III-5213 -  missing border to VideoUploadBox

---

src/pages/steps/AdditionalInformationStep/MediaStep.tsx

- Fix youtube thubmnail when share url has multiple query params
---
Ticket: https://jira.uitdatabank.be/browse/III-5243

III-5243 - Fix missing youtube thubmnail

---

src/pages/steps/AdditionalInformationStep/MediaStep.tsx
src/utils/promise.ts

- Use https to get vimeo thumbnails 
- Show successful video thumbnails instead of 0 if an api calls fails
- `Blocked loading mixed active content "http://vimeo.com/api/v2/video/117686240.json"`
---
Ticket: https://jira.uitdatabank.be/browse/III-5238

III-5238 - Show broken vimeo video thumbnails

---

package.json
src/hooks/useHandleSocketMessage.js
src/layouts/joblogger/JobLogger.tsx
yarn.lock

- Revert socketio back to old version
Since the newer dependencies aren't working just yet. I'll revert these changes so that new deploys to production don't get blocked.

Revert socketio back to old version

---

src/pages/steps/modals/PublishLaterModal.tsx

- minDate in publish later modal
---
Ticket: https://jira.uitdatabank.be/browse/III-5260

III-5260 - Add minDate in publish later modal to avoid publishing

---

global.d.ts
package.json
src/pages/steps/AdditionalInformationStep/PriceInformation.tsx
yarn.lock

- Refactor PriceInformation form to optimistic updates
---
Ticket: https://jira.uitdatabank.be/browse/III-5256
It wasn't originally my intention to refactor the form entirely, but due to the multiple tickets revolving around issues with out of sync states and such, and the suggestion to move to optimistic updates in the ticket, I felt it was perhaps the way to go so I went all in.
The diff is a bit scary but the crux of the changes are the following:
1. I moved a bunch of things up and down to group related things more closely together. 
2. I moved the "unique name" validation to Yup to be able to use the same logic for all errors and validation.
3. I removed most local states in order to use the form's data as state directly (which was the crux of most out of sync issues)
4. I made the …

Refactor PriceInformation form to optimistic updates

---

src/pages/steps/AdditionalInformationStep/PriceInformation.tsx

- Fix warning icon not appearing on Price tab when picking UiTPas organizer
---
Ticket: https://jira.uitdatabank.be/browse/III-5276

Fix warning icon not appearing on Price tab when picking UiTPas organizer

---

src/ui/TimeSpanPicker.tsx

- Simplify time filtering logic
---
Ticket: https://jira.uitdatabank.be/browse/III-5247
The times are now always filtered based on the starting time since the ending time will always be dependant on it. This prevents the issue where dropdowns gradually had less and less items and the issue where the default ending time of 23:59 would mean nothing in the dropdown.

Simplify time filtering logic

---

src/pages/steps/AdditionalInformationStep/PriceInformation.tsx

- Add back missing error filtering throwing empty errors and silently failing validation
---
Ticket: https://jira.uitdatabank.be/browse/III-5317
Seems one of the merges conflict resolution resulted in this incorrect code without the `errors` filtering, resulting in validation still failing silently

Add back missing error filtering throwing empty errors and silently failing validation

---

src/pages/steps/LocationStep.tsx
src/pages/steps/PlaceStep.tsx

- `LocationStep`: move maxWidth to inputField
---
Ticket: https://jira.uitdatabank.be/browse/III-5273

III-5273 - Move maxWidth to inputField

---

src/pages/PictureUploadBox.tsx
src/pages/steps/modals/PictureUploadModal.tsx

-Use same imageIcon in `PictureUploadModal` as in `PictureUploadBox`
---
Ticket: https://jira.uitdatabank.be/browse/III-5304

III-5304 - Use same imageIcon in PictureUploadModal as in PictureUploadBox

---

src/pages/steps/PlaceStep.tsx

- Always show "Create new location" prompt even if one has the same name
---
To be clear I don't know why the library behaves differently when passing true or returning true from a function, I found it in a Github issue, but seems to work 🤷‍♀️ 
Ticket: https://jira.uitdatabank.be/browse/III-5319

Always show "Create new location" prompt even if one has the same name

---

src/pages/steps/NameAndAgeRangeStep.tsx
src/pages/steps/NameStep.tsx
src/pages/steps/Steps.tsx
src/pages/steps/StepsForm.tsx
src/pages/steps/hooks/useEditField.ts

- Only trigger Steps onChange if they are dirty
- Make `Name` field always use the offer's main language instead of NL or the UI's
---
The reason for the Name change is because, since my offers have `fr` as main language, the code would always backfill `nl`, causing the field to be dirty when it wasn't. I also figured this was the correct way the code should behave but since the localization of the app has some edge cases I'm not sure this is correct or not.
I was also unsure of the best way to retrieve the offer's main language all the way down to the field since we only keep the ID for most of the components chain, so if there's a terser way that doesn't require passing so many props I'm up for it. I used the query cache in the mutation part but it's not always the safest option I think …

Only submit steps if they have changed

---

src/pages/steps/modals/PictureUploadModal.tsx

- Fix images in PictureUploadModal being wider than modal
---
Ticket: https://jira.uitdatabank.be/browse/III-5343

Fix images in PictureUploadModal being wider than modal

---

src/layouts/Sidebar.tsx

Hide beta toggle for now

---

src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json
src/pages/steps/CalendarStep/CalendarOptionToggle.tsx
src/ui/DatePicker.tsx

- missing translations
- [Use i18n.language for react-datepicker](https://github.com/cultuurnet/udb3-frontend/commit/7c39f757ed6fa1c4693f11bac32f48e501960428)
---
Ticket: https://jira.uitdatabank.be/browse/III-5314

III-5314 - Added missing translations

---

src/pages/steps/AdditionalInformationStep/PriceInformation.tsx

- Increase min-width of price category
**Before:**
**After:**
---
Ticket: https://jira.uitdatabank.be/browse/III-5374

III-5374 - Increase min-width of price category

---

src/layouts/Sidebar.tsx
src/pages/beta-version.page.tsx

- [Set toggle to false when canceled](https://github.com/cultuurnet/udb3-frontend/pull/645/commits/13ce5ce54d749367d8a7fc911aa473937d156a8f)
- [Set maxWidth to initial for Paragraphs on beta page](https://github.com/cultuurnet/udb3-frontend/pull/645/commits/f8d066af66500dac870f486ddc762cc1ae8c300a)
- [Set max width to 75%](https://github.com/cultuurnet/udb3-frontend/pull/645/commits/4c75661c905de96c6a5c3ab42d9989c26b472b6b)
- [Add padding to preview menu item in sidebar](https://github.com/cultuurnet/udb3-frontend/pull/645/commits/b5721aed854cd23a1fd9ea03124a058a52154a6b)
- [Use location.href to fix redirects not working after state/cookie change](https://github.com/cultuurnet/udb3-frontend/pull/645/commits/6a8077a3c22c827cdb30ae07ef29d02903844c26)
---
Ticket: …

III-5220 - Fix issues beta version

---

next.config.js

- [Ignore eslint during build](https://github.com/cultuurnet/udb3-frontend/commit/4346e020148faaf4e1706807f9feff711c35d7aa)
- [Ignore typescript during build](https://github.com/cultuurnet/udb3-frontend/commit/069b67677b81ac797c70aaae80c20849028e217b)
This is a small improvement.
Since we always require typescript and eslint to succeed before merging a PR, those shouldn't be necessary anymore when the code is built on the server.
Improvement time build:
with eslint && typescript -> 57.97s
without eslint && typescript -> 45.43s
(Yes I removed the .next folder in between runs 😉)
No fan? No problem I can close the PR, the build time difference is not huge.

Ignore eslint and tsc during build

---

src/pages/steps/AdditionalInformationStep/OrganizerPicker.tsx

- [Get organizer name from object as labelKey](https://github.com/cultuurnet/udb3-frontend/commit/b7d5818af571aba7bb541e1e5f24238a33733dfe)
---
Ticket: https://jira.uitdatabank.be/browse/III-5415

III-5415 - Fix typeahead organiser

---

src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json

- Add missing Theater location translation
---
We have the translation for Theater as an event but not as a type of location from what I understand, so added it with the other ID.
Ticket: https://jira.uitdatabank.be/browse/III-5494

Add missing Theater location translation

---

src/pages/steps/AdditionalInformationStep/PriceInformation.tsx

- Allow . as decimal separators in prices
---
Since we use `Intl.NumberFormat` both `.` and `,` get automatically converted to `,` correctly already
https://user-images.githubusercontent.com/1321596/229780898-56224942-0ddc-474a-a606-29e5e0e068bf.mp4
Ticket: https://jira.uitdatabank.be/browse/III-5519

Allow . as decimal separators in prices

---

src/pages/steps/LocationStep.tsx
src/pages/steps/NameAndAgeRangeStep.tsx
src/pages/steps/hooks/useFooterStatus.ts

- Centralize logic checking if a location is set and fix Cuultuur case
- Fixed `place` attribute not being cleared when clicking on Change municipality/address
---
The one part I'm not sure I understand is why in these places we checked whether `streetAndNumber` is dirty instead of checking if it's set? Since this allows writing something in the field then deleting it, making the empty field pass as valid, is that intended for a particular usecase?
---
Ticket: https://jira.uitdatabank.be/browse/III-5492

Centralize logic checking if a location is set and fix Cuultuur event case

---

src/hooks/api/organizers.ts
src/pages/steps/AdditionalInformationStep/OrganizerPicker.tsx

- Add workaround to remove dummy organizers
---
This uses the workaround idea from @bertramakers which first sets a valid organizer then removes that one from the offer, so there is a slight "UI flash" but since this is for an edge case I think it's likely fine.
https://user-images.githubusercontent.com/1321596/232031362-134604f3-49c6-4135-a097-46ff951be7ef.mp4
Ticket: https://jira.uitdatabank.be/browse/III-5532

Add workaround to remove dummy organizers

---

src/pages/dashboard/index.page.tsx
src/types/Organizer.ts

-  isExternalCreator label on organizer dashboard
---
Ticket: https://jira.uitdatabank.be/browse/III-5327

III-5327 - Add isExternalCreator label on organizer dashboard

---

src/pages/steps/AdditionalInformationStep/DescriptionStep.tsx

- Ensure empty descriptions can still be sent with RTE
---
Ticket: https://jira.uitdatabank.be/browse/III-5421

Ensure empty descriptions can still be sent with RTE

---

src/pages/OrganizerAddModal.tsx

- Remove redundant "Invalid URL" error message when trying taken URL
- Fixed organization name not showing in alert prompt depending on language
---
Ticket: https://jira.uitdatabank.be/browse/III-5518

Small tweaks to "Existing organization" prompt alert

---

src/pages/steps/AdditionalInformationStep/DescriptionStep.tsx

- Preserve "Enter for new list item" behavior in RTE lists
---
Ticket: https://jira.uitdatabank.be/browse/III-5115

Preserve "Enter for new list item" behavior in RTE lists

---

src/hooks/api/authenticated-query.test.js
src/hooks/api/authenticated-query.ts
src/hooks/api/events.ts
src/hooks/api/images.ts
src/hooks/api/offers.ts
src/hooks/api/organizers.ts
src/hooks/api/places.ts
src/hooks/api/productions.ts
src/hooks/api/uitpas.ts

- `mutationKeys` to all mutations
- test for mutation cache mechanism
- only execute mutation when the payload is different to the previous payload of the mutation with the same cacheKey
---
Ticket: https://jira.uitdatabank.be/browse/III-5591

III-5591 - Only do mutation when payload is different

---

src/pages/steps/modals/PictureUploadModal.tsx

- `PictureUploadBox`: early return when no dirtyFields
---
Ticket: https://jira.uitdatabank.be/browse/III-5619

III-5619 - Early return when no dirtyFields

---

src/pages/steps/LocationStep.tsx

- Recent locations: filter out locations which have the property `duplicateOf`
---
Ticket: https://jira.uitdatabank.be/browse/III-5596

III-5596 - Filter out locations which have the property duplicateOf

---

src/pages/steps/AdditionalInformationStep/ContactInfoStep.tsx

- Don't show flash message when nothing changed in ContactInfostep
---
The extra requests were already fixed by #714 this just prevent the success flash messages from still firing
Ticket: https://jira.uitdatabank.be/browse/III-5617

Don't show flash message when nothing changed in ContactInfostep

---

src/utils/getLanguageObjectOrFallback.ts

- Fix getLanguageObjectOrFallback trying to use NL default when object is not localized
---
Ticket: https://jira.uitdatabank.be/browse/III-5595

Fix getLanguageObjectOrFallback trying to use NL default when object is not localized

---

src/pages/steps/AdditionalInformationStep/PriceInformation.tsx

- alert galore on `PriceInformation` step
---
Ticket: https://jira.uitdatabank.be/browse/III-5313

III-5313 - Fix alert galore on PriceInformation

---

src/middleware.api.ts

- redirect loop when logged out and `auth0.redirect_uri` is still in cookie
---
Ticket: https://jira.uitdatabank.be/browse/III-5645

III-5645 - Fix redirect loop

---

package.json
src/hooks/api/user.ts
src/hooks/useCookiesWithOptions.ts
src/middleware.api.ts
src/pages/dashboard/index.page.tsx
src/pages/events/[eventId]/availability.multiple.test.js
src/pages/events/[eventId]/availability.single.test.js
src/pages/places/[placeId]/availability.test.js
src/utils/fetchFromApi.ts
src/utils/getApplicationServerSideProps.js
yarn.lock

- [jwt-decode package](https://github.com/cultuurnet/udb3-frontend/pull/749/commits/0e18f197082ff9ce6087004cc38217fb05018df5)
- [Get userInfo based on decoded idToken instead of api call](https://github.com/cultuurnet/udb3-frontend/pull/749/commits/fa119ffe0085e53859ce9a92b53110b5fe00131a)
- [unnecessary apiUrl argument in fetchFromApi](https://github.com/cultuurnet/udb3-frontend/pull/749/commits/d88f96da7fba07a7df4e84d4deef1f0e245b2ba6)
- too many calls to auth0 /userInfo endpoint
---
Ticket: https://jira.uitdatabank.be/browse/III-5642

III-5642 - Fix too many calls to /userInfo

---

src/pages/steps/AdditionalInformationStep/PriceInformation.tsx

- Check if price form is dirty before triggering invalidation
---
This does not affect PUT requests since that'll be fixed separately through the mutation change. This only conditionally avoids triggering the `onSuccess` callback when no data has changed, which invalidates the step and refetches the offer.
Since we replace the form's values on load, it marks all fields as dirty. Using `reset({}, {keepValues: true})` does not touch any of the data but only resets form states (like dirty/touched) which allows us to rely on that to check if the form is dirty or not.
---
Ticket: https://jira.uitdatabank.be/browse/III-5626

Check if price form is dirty before triggering invalidation

---

src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json
src/pages/OrganizerAddModal.tsx

- Regex for dutch zip codes
```javascript
var regex = /^\d{4}([A-Za-z0-9]{2})?$/;
console.log(regex.test("1234"));       // true
console.log(regex.test("1234AB"));     // true
console.log(regex.test("123"));        // false, less than 4 digits
console.log(regex.test("12345"));      // false, more than 4 digits
console.log(regex.test("1234ABC"));    // false, more than 2 alphanumeric characters
console.log(regex.test("1234AB7"));    // false, more than 2 alphanumeric characters
```
- Copy for example dutch zip code
---
Ticket: https://jira.uitdatabank.be/browse/III-5719

III-5719 - Fix incorrect validation of dutch zip codes

---

src/layouts/Announcements.js

- Prevent images from being stretched in the Announcements
---
I opted for an `object-fit` instead of removing the `max-height` altogether so that the text of the announcement isn't pushed out of view either
Ticket: https://jira.uitdatabank.be/browse/III-5747

Prevent images from being stretched in the Announcements

---

src/hooks/api/authenticated-query-v2.ts
src/hooks/api/authenticated-query.ts
src/hooks/api/useHeaders.ts
src/hooks/api/user.ts
src/hooks/useFeatureFlag.ts
src/layouts/Sidebar.tsx
src/layouts/index.tsx
src/pages/dashboard/index.page.tsx
src/pages/events/[eventId]/duplicate/index.page.tsx
src/pages/events/[eventId]/edit/index.page.tsx
src/pages/manage/movies/[eventId]/edit.page.tsx
src/pages/steps/AdditionalInformationStep/OrganizerPicker.tsx
src/pages/steps/LocationStep.tsx
src/pages/test.page.tsx
src/redirects.tsx
src/utils/getApplicationServerSideProps.ts

- Update user queries to new query function
---
Ticket: https://jira.uitdatabank.be/browse/III-5778

Update user queries to new query function

---

src/pages/VideoLinkAddModal.test.ts
src/pages/VideoLinkAddModal.tsx

- Add support for Youtube Shorts URLs in the front-end
---
Ticket: https://jira.publiq.be/browse/III-5765

Add support for Youtube Shorts URLs in the front-end

---

src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json
src/pages/steps/AdditionalInformationStep/AdditionalInformationStep.tsx
src/pages/steps/AdditionalInformationStep/PhysicalLocationStep.tsx
src/test/e2e/create-organizer.spec.ts

- [optional titleKey prop to additionalInformation to make title of tabs more configurable](https://github.com/cultuurnet/udb3-frontend/commit/be079f225241c5cd3a4bfbd02316f7081b16907f)
- Organizer form: change title of location tab to 'Adres'
---
Ticket: https://jira.uitdatabank.be/browse/III-5845

III-5845 - Organizer form: change title of location tab to 'Adres'

---

src/pages/steps/AdditionalInformationStep/LabelsStep.tsx
src/pages/steps/LocationStep.tsx

- Fix some Additional Steps jumping around
---
The issue was:
- The LocationStep not respecting `minHeight` and thus having a different height than the other tabs (causing jumping)
- The main labels input having an ID of `labels` making the browser scroll to it on opening the tab (because of the #hash feature)
Ticket: https://jira.publiq.be/browse/III-5844

Fix some Additional Steps jumping around

---

src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json

- `<ul>` to description_tips translation labels
---
Ticket: https://jira.uitdatabank.be/browse/III-5849

III-5849 - Add <ul> to description_tips

---

src/styles/GlobalStyle.js

- Remove duplicate padding at top of RTE
---
When we changed the newline behavior to only paragraphs it meant every block in Draft is a `<p>` by default which comes with some vertical padding. This was duplicating with the editor's own padding.
Ticket: https://jira.publiq.be/browse/III-5866

Remove duplicate padding at top of RTE

---

src/pages/OrganizerAddModal.tsx
src/pages/steps/AdditionalInformationStep/ContactInfoStep.tsx

- Fixed invalid contact information being saved if others are valid
---
The issue was that the step is not an actual form, so one field being invalid wouldn't prevent saving everything since errors are displayed on a per-field basis. So I now filter out invalid information from the contact info being sent as payload to at least avoid the bug.
I also removed the `isOrganizer` prop since we can rely on the scope now, and it was used to signify the step was used in a modal and should not do requests. So I changed it to check for `offerId` since it's only provided by AdditionalSteps and it was less confusing now that the step is actually used for organizers in a different context which requires sending requests.
Ticket: https://jira.publiq.be/browse/III-5883

Fixed invalid contact information being saved if others are valid

---

src/pages/steps/AdditionalInformationStep/OrganizerStep.tsx

- Fixed  Uitpas card systems checked state sometimes being incorrect
---
When I converted the card system stuff to optimistic I didn't account for an edge case which resulted in the card system state to not be populated properly. I removed the special condition and wasn't able to reproduce the old out of sync state it was added for so I think this version should be good to go.
Ticket: https://jira.publiq.be/browse/III-5881

Fixed  Uitpas card systems checked state sometimes being incorrect

---

src/pages/steps/AdditionalInformationStep/MediaStep.tsx

-  Use `mainImage` property for organizers instead of `image`
---
Ticket: https://jira.uitdatabank.be/browse/III-5890

III-5890 - Use mainImage property for organizers instead of image

---

src/hooks/api/organizers.ts

- Disable refetchOnWindowFocus for getOrganizerByIdQuery (just like for event)
---
Ticket: https://jira.uitdatabank.be/browse/III-5884

III-5884 - Disable refetchOnWindowFocus for getOrganizerByIdQuery

---

src/layouts/Sidebar.tsx
src/pages/login/[language].page.tsx

For some reason this commit: https://github.com/cultuurnet/udb3-frontend/pull/815/commits/11788c4390088c6797874b7e969694ab90e196d6 broke the login / logout functionality on acceptance.
It's something we already experienced in the past that's why we use `window.location.assign` instead of `router.push`

Fix login / logout

---

src/pages/steps/modals/PictureUploadModal.tsx

- Fixed Add Image modal closing when errors are present
---
There was a bit of logic to simply close the modal if nothing was changed in it but it wasn't checking all fields, this ensures we don't close it if the user changed anything or uploaded a media
Ticket: https://jira.publiq.be/browse/III-5910

Fixed Add Image modal closing when errors are present

---

src/pages/steps/LocationStep.tsx

- [Also reset location after selecting the online toggle](https://github.com/cultuurnet/udb3-frontend/commit/2c28d9582e4d784ed1ee2af9bc82ae1b4fca4101)
- CultuurkuurInfo visible in the wrong cases
---
Ticket: https://jira.uitdatabank.be/browse/III-5932

III-5932 - Also reset location after selecting the online toggle

---

src/ui/Typeahead.tsx

- Disable caching of typeahead entries
https://github.com/ericgio/react-bootstrap-typeahead/blob/HEAD/docs/API.md#props-1
---
Ticket: https://jira.uitdatabank.be/browse/III-5897

III-5897 - Disable caching of typeahead

---

src/styles/GlobalStyle.js

- Override default success progress bar color
---
Since we embed Bootstrap from CDN I wasn't able to customize the variables so this is a bit of a bandaid but we can revisit if we have more usecases like this.
Ticket: https://jira.publiq.be/browse/III-5936

Override default success progress bar color

---

next.config.js
package.json
sentry.client.config.js
sentry.edge.config.js
sentry.server.config.js
src/pages/_error.jsx
src/pages/events/[eventId]/duplicate/index.page.tsx
yarn.lock

- Enabled Sentry replays and sourcemaps
- Fixed potential crash in duplicate logic (but not likely the root cause)
---
Example replay https://publiq-vzw.sentry.io/replays/9dde7d2fca214758ae080de3d96021fa/?t=1018&t_main=breadcrumbs
Ticket: https://jira.publiq.be/browse/III-5672

Fixed potential crash and enable Sentry replays/sourcemaps

---

src/hooks/useFeatureFlag.ts
src/redirects.tsx

- Add feature flag for new duplicate
---
Because the Angular app still points to the Angular duplication, this is all that is needed to revert the new duplication logic unless the corresponding feature flag is present.
Ticket: https://jira.publiq.be/browse/III-5672

Add feature flag for new duplicate

---

src/pages/steps/AdditionalInformationStep/BookingInfoStep.tsx

- Don't use `Object.hasOwn()` since it's only supported in node 16.19
---
Ticket: https://jira.uitdatabank.be/browse/III-5948

III-5948 - Don't use Object.hasOwn since it's only supported in node 16.19

---

src/utils/getLanguageObjectOrFallback.ts

- `getLanguageObjectOrFallback` add early return if obj is undefined
- `getLanguageObjectOrFallback` Don't make page crash if there's no object at all
---
Ticket: https://jira.uitdatabank.be/browse/III-5947

III-5947 - Don't make page crash if there's no object at all

---

src/layouts/Sidebar.tsx
src/pages/steps/StepsForm.tsx

- Use url param to trigger hotjar survey on /preview.
Since hotjar was triggered before a route push, the hotjar survey was only visible in a flash. 
Now the hotjar survey will be triggered by the `hj` param in the url
---
Ticket: https://jira.uitdatabank.be/browse/III-5882

III-5882 - Use url param to trigger hotjar survey on /preview

---

src/pages/RichTextEditor.tsx

- Ensure pasting rich text strips non supported styling
---
I'm not sure I can fix it retroactively without some intervention from the back-end but this will prevent future unwanted HTML to make it to descriptions.
https://github.com/cultuurnet/udb3-frontend/assets/1321596/d041f9fd-efd0-4f49-ab75-89ff807bb160
Ticket: https://jira.publiq.be/browse/III-5951

Ensure pasting rich text strips non supported styling

---

src/pages/steps/AdditionalInformationStep/FormScore.tsx

- [Slightly modify subArcs EventScore barometer](https://github.com/cultuurnet/udb3-frontend/commit/74f01b082c7e62e1effee67cd512fdf5ec35cb43)
Screenshots:
---
Ticket: https://jira.uitdatabank.be/browse/III-6009

III-6009 - Slightly modify subArcs EventScore barometer

---

next.config.js
src/pages/api/robots/index.api.ts

- [/api/robots rewrite in next.config](https://github.com/cultuurnet/udb3-frontend/commit/d3d05bd243e9e43f2e5691a1609c1a1caacb7402)
- [robots.txt](https://github.com/cultuurnet/udb3-frontend/commit/d2d6194ce87f87d14f201aff39ca67aebd26a0f4)
This is how the production sitemap will look like (I took some things over from the uitinvlaanderen.be/robots.txt).
On **production** we don't the robots to scan anything which isn't the homepage / login page.
On the other environments, no robots are allowed at all.
There's a tool which allows you to test your sitemap.
See: https://technicalseo.com/tools/robots-txt/
---
Ticket: https://jira.uitdatabank.be/browse/III-6141

III-6141 - Add dynamic robots.txt

---

src/pages/PlaceAddModal.tsx
src/ui/FormElement.tsx

- [Add clarifying copy in location modal of event entry form](https://github.com/cultuurnet/udb3-frontend/commit/a2b0d00085c346c23d743dea82cc6b15e6589865)
- [Position characterCounter next to info if defined](https://github.com/cultuurnet/udb3-frontend/commit/02ca59da5669aa719b0172c515f877fe6fe3638b)
Screenshot
---
Ticket: https://jira.uitdatabank.be/browse/III-6090

III-6090 - Add clarifying copy in location modal of event entry form 

---

src/pages/steps/StepsForm.tsx

- Fixed offer background updates overwriting currently edited values
---
I thought `keepDirty` kept the actual values but it seems it only keeps the boolean state, meaning values that are still being edited when anything triggers a refetch (such as a window blur/focus) would revert the empty value to its original filled value.
Ticket: https://jira.publiq.be/browse/III-5839

Fixed offer background updates overwriting currently edited values

---

src/pages/steps/AdditionalInformationStep/PriceInformation.tsx

- Fixed setting price to free not triggering validation refresh
---
Overriding the price value does not seem to trigger the `useEffect` that handles validation, neither did trying to refetch or invalidate or blur the fields or something. Since this form has been a lot of back and forth to make it both reactive and optimistic I just reset the offer data to trigger the effect, although I'm still confused as to why that's the only solution that seems to work but since we handle the price mutation in a special way I'm guessing it's related? 
I'm unsure why `refetch` doesn't work but `remove` does, I thought both would yield the same result in the end but could be mistaken since the data is automatically refetched upon removal but I don't know 🤔 
Ticket: https://jira.publiq.be/browse/III-6008

Fixed setting price to free not triggering validation refresh

---

src/pages/[...params].page.js

- List /404 as default not found path to allow manual 404s within Angular
---
Ticket: https://jira.publiq.be/browse/III-5993
Needs https://github.com/cultuurnet/udb3-angular-app/pull/213 and https://github.com/cultuurnet/udb3-angular/pull/779

List /404 as default not found path to allow manual 404s within Angular

---

src/pages/steps/AdditionalInformationStep/OrganizerPicker.tsx
src/ui/Typeahead.tsx

- Fixed Typeahead items not wrapping properly
---
Before:
After:
---
Ticket: https://jira.publiq.be/browse/III-6218

Fixed Typeahead items not wrapping properly

---

src/i18n/de.json
src/i18n/nl.json
src/pages/steps/AdditionalInformationStep/OrganizerPicker.tsx
src/ui/Typeahead.tsx

- Fixed truncating of Organizer picker
---
The problem was mainly with the extra wrapping span added by the `Inline`, so I moved the logic to plain CSS, but since targeting the element itself messed more with the other dropdowns I moved the styling purely to the Organizer picker instead of the main Typeahead.
Ticket: https://jira.publiq.be/browse/III-6218

Fixed truncating of Organizer picker

---

src/pages/steps/AdditionalInformationStep/OrganizerStep.tsx

- Fixed invalid organizers causing crashes on offer views
---
Seems some offer have "phantom" organizers that don't exist in the DB but still get embedded, this is just to ignore those and prevent crashes where the logic expect Organizer properties to be present.
Ticket: https://jira.publiq.be/browse/III-6237

Fixed invalid organizers causing crashes on offer form

---

src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json

- Copy about the max length of price tariff names
Note that this is a quick solution, and we might think of an extra one (validation / counter / progress bar), etc. just like we have for the title of an event or place.
---
Ticket: https://jira.uitdatabank.be/browse/III-6305

Add copy about max length of a price tariff

---

src/pages/dashboard/DashboardRow.tsx
src/pages/dashboard/index.page.tsx

- imageUrl
- css
---
Ticket: https://jira.uitdatabank.be/browse/III-6039

III-6039 - Improve dashboard styling

---

next.config.js
package.json
patches/@auth0+nextjs-auth0+2.4.0.patch
yarn.lock

- [Add patch-package](https://github.com/cultuurnet/udb3-frontend/pull/936/commits/f561baea6ff24b21d91951ddfb103db73628ae01)
- [Patch auth0 package](https://github.com/cultuurnet/udb3-frontend/pull/936/commits/a98c0851258ed9a058bffe86d523bbdf1d18b704)
I first tried to depend on my fix on the official auth0 package.
But that meant updating the auth0 package, which meant updating react to 18 and in turn related packages.
It wasn't that trivial to do. mainly xstate/react.
---
Ticket: https://jira.uitdatabank.be/browse/III-6343

III-6343 - use fixed auth0 package

---

package.json
src/pages/steps/LocationStep.tsx
src/test/e2e/create-place.spec.ts
src/ui/Inline.tsx
yarn.lock

- Only show Blank Street toggle for organizers, not offers
---
Ticket: https://jira.publiq.be/browse/III-6384

Only show Blank Street toggle for organizers, not offers

---

src/hooks/api/ownerships.ts
src/pages/organizers/[organizerId]/ownerships/OwnershipsTable.tsx
src/pages/organizers/[organizerId]/ownerships/index.page.tsx

- useGetOwnershipCreatorQuery
---
Ticket: https://jira.uitdatabank.be/browse/III-6393

III-6393 - Display creator email

---

src/pages/organizers/[organizerId]/ownerships/OwnershipsTable.tsx
src/test/e2e/create-organizer.spec.ts
src/ui/Alert.tsx

- Added end-to-end test for ownership
---
Missing approval/rejection but not sure how to test it, although requesting an ownership technically uses the approval logic under the hood so we know it works in that way at least.
Ticket: https://jira.publiq.be/browse/III-6417

Added end-to-end test for ownership

---

src/pages/organizers/[organizerId]/preview/index.page.tsx

- Make back button on organizer preview go to previous URL always
---
Ticket: https://jira.publiq.be/browse/III-6423

Make back button on organizer preview go to previous URL always

---

src/pages/organizers/[organizerId]/ownerships/OwnershipsTable.tsx

- Ensure Ownerships table don't crash on missing creator prop (cf. pending table)
---
Spotted as part of https://jira.publiq.be/browse/III-6146 but unrelated to the described problem (besides that the page crashes on this also)
---
I just don't understand why Typescript doesn't flag `creator` as nullable here even though the prop explicitely states that it is a few lines above 🤔 This should have been caught by the static analysis normally

Ensure Ownerships table don't crash on missing creator prop (cf. pending table)

---

src/pages/dashboard/index.page.tsx

- Don't render suggested organizers section in dashboard if none present
---
Currently you see the title and alert but not the table so it's confusing
Ticket: https://jira.publiq.be/browse/III-6361

Don't render suggested organizers section in dashboard if none present

---

package.json
yarn.lock

- Update to latest minor version of @sentry/nextjs
- Fix issue sentry on node 22
https://github.com/getsentry/sentry-javascript/pull/10938
Ticket: https://jira.publiq.be/browse/III-6355

III-6355 - Fix issue sentry on node 22

---

src/hooks/api/events.ts
src/hooks/api/labels.ts
src/hooks/api/offers.ts
src/hooks/api/organizers.ts
src/hooks/api/ownerships.ts
src/hooks/api/places.ts
src/hooks/api/productions.ts
src/hooks/api/uitpas.ts
src/hooks/api/user.ts
src/utils/fetchFromApi.ts
src/utils/handleErrorObject.ts

- [Infer different return type depending on silentError](https://github.com/cultuurnet/udb3-frontend/commit/21ec91846be87919a9f09537583ab8e7c5862adc)
- [Remove unneeded checking of error object](https://github.com/cultuurnet/udb3-frontend/commit/aecdb0a30ca8241356fc7b8888478ae76fb2093d)
> This is needed to correctly infer the data returned from queryFns.
> At the moment this is TData | void because of the returns we do when it is an error object
---

III-6516 - Fix inference fetch from api

---

src/layouts/Sidebar.tsx
src/pages/404.page.js
src/pages/Footer.tsx
src/ui/Alert.tsx
src/ui/Box.tsx
src/ui/Inline.tsx
src/ui/Notification.tsx
src/ui/RadioButtonWithLabel.tsx
src/ui/Stack.tsx
src/ui/Typeahead.tsx

- Reduced amount of console warnings
---
Ticket: https://jira.publiq.be/browse/III-6514

Reduce amount of console warnings

---

src/pages/dashboard/DashboardRow.tsx
src/pages/dashboard/index.page.tsx
src/test/e2e/dashboard.spec.ts

- Fixed deletion modal not showing on dashboard
- Fixed offers not disappearing on dashboard after deletion
- Fixed React warning about duplicate `divider` keys in offer dropdowns
---
Because `Page` only accepts children [that are Page slots](https://github.com/cultuurnet/udb3-frontend/blob/main/src/ui/Page.tsx#L28), it would discard the Modal in the `filter`ing being done of the raw children. Putting it in one of the slots makes it render in the DOM again.
I also weirdly had to switch to manually await for the queries invalidation, otherwise the cache gets busted but the refetch doesn't trigger. Not entirely sure why as to me a Promise returned from an `onSuccess` would be resolved but maybe not.
Ticket: https://jira.publiq.be/browse/III-6547

Fixed deletion modal not showing on dashboard

---

src/pages/organizers/[organizerId]/preview/index.page.tsx

- Removed back button from organizer preview page
---
Ticket: https://jira.publiq.be/browse/III-6503

Removed back button from organizer preview page

---

src/hooks/api/ownerships.ts
src/pages/organizers/[organizerId]/preview/RequestOwnershipModal.tsx

- [ownerId param from requestOwnership mutation](https://github.com/cultuurnet/udb3-frontend/commit/f7bb0f50ff681d0d0da75dd28cc05dc46a55ec74)
---
Ticket: https://jira.uitdatabank.be/browse/III-6701

III-6701 - Remove ownerId param from requestOwnership mutation

---

src/pages/steps/AdditionalInformationStep/OrganizerPicker.tsx

- OrganizerPicker: [Don't return anything if organizer doesn't have a name](https://github.com/cultuurnet/udb3-frontend/commit/afb61338e68400b73f52c2aa8a69c5951506f8de)
- TypeError: can't access property "undefined", e.name is undefined
**Cause:**
One of the recent events has an organizer which has been deleted (and doesn't have a name):
---
Ticket: https://jira.publiq.be/browse/III-6779

III-6779 - Don't return anything if organizer doesn't have a name

---

src/hooks/api/labels.ts
src/hooks/useUitpasLabels.tsx
src/pages/steps/AdditionalInformationStep/OrganizerPicker.tsx
src/pages/steps/AdditionalInformationStep/OrganizerStep.tsx
src/pages/steps/AdditionalInformationStep/PriceInformation.tsx
src/utils/reconcileRates.test.ts
src/utils/reconcileRates.ts

- [useGetUitpasLabelsQuery hook for fetchin uitpas labels](https://github.com/cultuurnet/udb3-frontend/commit/da72a9737c77ff74143b56cb95a6aeec2e422493)
- [hook useUitpasLabels](https://github.com/cultuurnet/udb3-frontend/commit/819a1368a1f2c251145e09c7c6aece24f910b287)
- Use list of uitpas labels from api instead of check on fixed string uitpas | paspartoe
---
Ticket: https://jira.uitdatabank.be/browse/III-6775

III-6775 - Use uitpas labels from API for uitpas organizer check

---

src/i18n/de.json
src/i18n/fr.json
src/i18n/nl.json
src/pages/organizers/[organizerId]/preview/RequestOwnershipModal.tsx

- [translations for ownership request errors](https://github.com/cultuurnet/udb3-frontend/commit/d5351a39a3bd6f28d52c72153bac52729ef663d6)
- [specific errorMessage for ownership request](https://github.com/cultuurnet/udb3-frontend/commit/6320b1741e41d84e563d2de3c5203d293480b345)
- [userId, since it's not necessary](https://github.com/cultuurnet/udb3-frontend/commit/e055b593326207bc5df9aa9583f12ace5cb1bac6)
- [unused imports and const](https://github.com/cultuurnet/udb3-frontend/commit/183e608bbf10475624ff8f91495e16887056995a)
---
Ticket: https://jira.uitdatabank.be/browse/III-6778

III-6778 - Show specific error message when ownership request throws a 409

---

src/pages/steps/EventTypeAndThemeStep.tsx
src/pages/steps/hooks/useAddOffer.ts

- [Only show error when there are actual themes](https://github.com/cultuurnet/udb3-frontend/pull/1082/commits/2cf7a8afc3eebb3e8e35394987a54bce5de75e48)
- [Don't push error when eventType has no themes](https://github.com/cultuurnet/udb3-frontend/pull/1082/commits/e66b945bf02e7bff4908c943339b1ec6a1b3b65f)
---
Ticket: https://jira.publiq.be/browse/III-6802

III-6802 - Ck don't show error on themes when there are no themes for types
